In [1]:
import numpy as np 
import pandas as pd

In [2]:
#avoide missing any row r column 

pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [3]:
df = pd.read_csv('flats.csv')
df.sample(5)

,property_name,link,society,price,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id,price_num,area_num,price_per_sqft
885,3 BHK Flat in F-11,https://www.zameen.com/3-bhk-bedroom-apartment...,F-11 Homes,"36,559,285 PKR",Carpet area: 1015 (94.3 sq.m.),3,4,1,NaN,"133 Street F-11, Islamabad, Pakistan",1 of 20 Floors,North-East,5 to 10 Year Old,"['Police Station', 'Mosque', 'Hospital']",3 BHK Flat in F-11 located in F-11 Homes. Appr...,"['Wardrobe', 'Curtains', 'AC', 'Dining Table',...","['Swimming Pool', 'Security Personnel', 'Power...",3.2 ★,ISB000886,36559285.0,1015,36019.0
2636,2 BHK Flat in G-9,https://www.zameen.com/2-bhk-bedroom-apartment...,G-9 Heights,"8,420,760 PKR",Carpet area: 810 (75.25 sq.m.),2,3,2,Prayer Room,"12 Block G-9, Islamabad, Pakistan",3 of 20 Floors,South-East,Under Construction,"['MetroBus Station', 'Mosque', 'University', '...",2 BHK Flat in G-9 located in G-9 Heights. Appr...,"['Fridge', 'AC', 'Wardrobe', 'Washing Machine'...","['Visitor Parking', 'Lift(s)']",3.9 ★,ISB002637,8420760.0,810,10396.0
1048,2 BHK Flat in G-13,https://www.zameen.com/2-bhk-bedroom-apartment...,G-13 Residency,"15,188,316 PKR",Carpet area: 858 (79.71 sq.m.),2,2,0,Prayer Room,"171 Block G-13, Islamabad, Pakistan",11 of 8 Floors,West,5 to 10 Year Old,"['School', 'Bus Stop']",2 BHK Flat in G-13 located in G-13 Residency. ...,"['TV', 'Sofa', 'Dining Table', 'Fridge', 'Geys...","['Lift(s)', 'Swimming Pool', 'Security Personn...",3.4 ★,ISB001049,15188316.0,858,17702.0
2392,2 BHK Flat in F-7,https://www.zameen.com/2-bhk-bedroom-apartment...,F-7 Plaza,"15,829,911 PKR",Carpet area: 621 (57.69 sq.m.),2,3,1,Study Room,"117 Sector F-7, Islamabad, Pakistan",5 of 25 Floors,North,10+ Year Old,"['Mosque', 'Bus Stop', 'Hospital', 'Supermarke...",2 BHK Flat in F-7 located in F-7 Plaza. Approx...,"['Washing Machine', 'Curtains', 'Wardrobe', 'N...","['Park', 'Swimming Pool', 'CCTV', 'Community C...",4.1 ★,ISB002393,15829911.0,621,25491.0
2876,1 BHK Flat in E-11,https://www.zameen.com/1-bhk-bedroom-apartment...,E-11 Residency,"4,481,477 PKR",Carpet area: 481 (44.69 sq.m.),1,1,1,Servant Room,"220 Street E-11, Islamabad, Pakistan",6 of 3 Floors,North-East,1 to 5 Year Old,"['Mosque', 'Shopping Mall']",1 BHK Flat in E-11 located in E-11 Residency. ...,"['TV', 'Wardrobe', 'Fridge', 'Geyser', 'No AC'...","['CCTV', 'Swimming Pool', 'Gym', 'Lift(s)']",3.0 ★,ISB002877,4481477.0,481,9317.0

In [4]:
#shape
df.shape

(3000, 22)

In [5]:
#info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3000 non-null   object
 1   link             3000 non-null   object
 2   society          3000 non-null   object
 3   price            3000 non-null   object
 4   areaWithType     3000 non-null   object
 5   bedRoom          3000 non-null   int64
 6   bathroom         3000 non-null   int64
 7   balcony          3000 non-null   int64
 8   additionalRoom   2397 non-null   object
 9   address          3000 non-null   object
 10  floorNum         3000 non-null   object
 11  facing           3000 non-null   object
 12  agePossession    3000 non-null   object
 13  nearbyLocations  3000 non-null   object
 14  description      3000 non-null   object
 15  furnishDetails   3000 non-null   object
 16  features         3000 non-null   object
 17  rating           3000 non-null   object
 18  property_id      3000 non-null   object
 19  price_num        3000 non-null   float64
 20  area_num         3000 non-null   int64
 21  price_per_sqft   3000 non-null   float64
dtypes: float64(2), int64(4), object(16)
memory usage: 515.8+ KB

In [6]:
#check for duplicate
df.duplicated().sum()

0

In [7]:
#check for missing values
df.isnull().sum()

property_name        0
link                 0
society              0
price                0
areaWithType         0
bedRoom              0
bathroom             0
balcony              0
additionalRoom     603
address              0
floorNum             0
facing               0
agePossession        0
nearbyLocations      0
description          0
furnishDetails       0
features             0
rating               0
property_id          0
price_num            0
area_num             0
price_per_sqft       0
dtype: int64

In [8]:
#to drop extra column
df.drop(columns = ['link','property_id'],inplace = True)

In [9]:
df.sample(5)

,property_name,society,price,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,price_num,area_num,price_per_sqft
1217,4 BHK Flat in E-11,E-11 Homes,"19,608,076 PKR",Carpet area: 1468 (136.38 sq.m.),4,5,1,Study Room,"160 Street E-11, Islamabad, Pakistan",2 of 6 Floors,East,1 to 5 Year Old,"['Police Station', 'University', 'Shopping Mal...",4 BHK Flat in E-11 located in E-11 Homes. Appr...,"['AC', 'No AC']","['24/7 Water Supply', 'Park']",4.9 ★,19608076.0,1468,13357.0
2744,1 BHK Flat in G-15,G-15 Heights,"8,173,121 PKR",Carpet area: 499 (46.36 sq.m.),1,1,0,Servant Room,"126 Street G-15, Islamabad, Pakistan",Ground of 8 Floors,North-East,10+ Year Old,"['Shopping Mall', 'Bus Stop']",1 BHK Flat in G-15 located in G-15 Heights. Ap...,"['Washing Machine', 'Sofa', 'Modular Kitchen',...","['Lift(s)', 'CCTV', 'Park']",3.6 ★,8173121.0,499,16379.0
873,2 BHK Flat in DHA Phase 2,DHA Phase 2 Heights,"10,087,511 PKR",Carpet area: 823 (76.46 sq.m.),2,2,3,NaN,"169 Sector DHA Phase 2, Islamabad, Pakistan",3 of 8 Floors,South,Ready to Move,"['Police Station', 'Hospital', 'Bus Stop']",2 BHK Flat in DHA Phase 2 located in DHA Phase...,"['Modular Kitchen', 'AC', 'Sofa', 'TV']","['Security Personnel', 'CCTV', 'Power Back-up'...",4.9 ★,10087511.0,823,12257.0
2377,1 BHK Flat in F-7,F-7 Homes,"15,705,978 PKR",Carpet area: 519 (48.22 sq.m.),1,1,1,Servant Room,"274 Sector F-7, Islamabad, Pakistan",2 of 6 Floors,North-West,10+ Year Old,"['Hospital', 'Supermarket', 'Park', 'School']",1 BHK Flat in F-7 located in F-7 Homes. Approx...,"['Washing Machine', 'Modular Kitchen', 'Dining...","['Gym', 'Swimming Pool', 'Lift(s)', 'Security ...",3.5 ★,15705978.0,519,30262.0
1264,3 BHK Flat in DHA Phase 2,DHA Phase 2 Residency,"23,646,360 PKR",Carpet area: 965 (89.65 sq.m.),3,3,1,Store Room,"17 Street DHA Phase 2, Islamabad, Pakistan",1 of 16 Floors,North,5 to 10 Year Old,"['Mosque', 'School', 'MetroBus Station', 'Hosp...",3 BHK Flat in DHA Phase 2 located in DHA Phase...,"['Geyser', 'Modular Kitchen', 'AC', 'Curtains'...","['Lift(s)', 'Community Center', 'Swimming Pool...",4.1 ★,23646360.0,965,24504.0

In [10]:
#df['society']

In [11]:
#to know categories
df['society'].value_counts().shape

(110,)

In [12]:
#df['society'].value_counts

In [13]:
df['society'].value_counts().shape

(110,)

In [14]:
#price
#df['price'].value_counts()

In [15]:
def price_to_crore(price_str):
    """
    Convert a price string like '5,666,150 PKR' into CRORE format.
    Returns a float value in crore.
    """
    import re
    
    # Remove PKR and commas
    clean = re.sub(r'[^\d.]', '', price_str)
    
    if clean == "":
        return None
    
    price = float(clean)
    
    # Convert to crore
    crore_value = price / 10000000  # 1 crore = 10,000,000
    
    return round(crore_value, 2)  # Rounded to 2 decimals

    df['price_in_crore'] = df['price'].apply(price_to_crore)

In [16]:
def convert_price_to_crore(price_str):
    """
    Converts a price value like '5,666,150 PKR' to crore format.
    Example: '5,666,150 PKR' -> 0.57 crore
    """
    import re
    
    # Remove PKR, commas, and spaces → keep only digits
    numeric = re.sub(r'[^\d]', '', price_str)
    
    if numeric == "":
        return None
    
    price = float(numeric)
    
    # Convert to crore (1 crore = 10,000,000)
    crore_value = price / 10000000
    
    return round(crore_value, 2)

    df['price_in_crore'] = df['price'].apply(price_to_crore)

In [17]:
df['price_in_crore'] = df['price'].apply(convert_price_to_crore)

In [18]:
df.drop(columns = ['price'],inplace = True)

In [19]:
df.sample(5)

,property_name,society,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,price_num,area_num,price_per_sqft,price_in_crore
2214,1 BHK Flat in Bahria Town,Bahria Town Residency,Carpet area: 405 (37.63 sq.m.),1,1,2,NaN,"17 Street Bahria Town, Islamabad, Pakistan",3 of 8 Floors,North-West,Under Construction,"['Mosque', 'University', 'Park', 'School']",1 BHK Flat in Bahria Town located in Bahria To...,"['Washing Machine', 'Dining Table']","['Lift(s)', 'Security Personnel', 'Visitor Par...",4.5 ★,4169475.0,405,10295.0,0.42
1583,1 BHK Flat in F-7,F-7 Heights,Carpet area: 420 (39.02 sq.m.),1,1,3,Servant Room,"258 Street F-7, Islamabad, Pakistan",3 of 8 Floors,North,Ready to Move,"['School', 'Hospital']",1 BHK Flat in F-7 located in F-7 Heights. Appr...,"['Dining Table', 'AC', 'No Fridge', 'Modular K...","['Lift(s)', 'Gym', 'Security Personnel', '24/7...",3.2 ★,9836820.0,420,23421.0,0.98
2877,3 BHK Flat in G-13,G-13 Plaza,Carpet area: 1171 (108.79 sq.m.),3,4,1,Prayer Room,"240 Sector G-13, Islamabad, Pakistan",5 of 3 Floors,South-East,Under Construction,"['Shopping Mall', 'Bus Stop']",3 BHK Flat in G-13 located in G-13 Plaza. Appr...,"['Wardrobe', 'TV']","['Community Center', 'Lift(s)', '24/7 Water Su...",4.9 ★,19107207.0,1171,16317.0,1.91
529,3 BHK Flat in G-6,G-6 Apartments,Carpet area: 995 (92.44 sq.m.),3,4,1,NaN,"182 Phase G-6, Islamabad, Pakistan",3 of 3 Floors,East,5 to 10 Year Old,"['School', 'Shopping Mall', 'Mosque', 'Police ...",3 BHK Flat in G-6 located in G-6 Apartments. A...,"['Sofa', 'AC']","['Visitor Parking', 'Swimming Pool', 'Communit...",4.1 ★,20685055.0,995,20789.0,2.07
370,3 BHK Flat in G-11,G-11 Residency,Carpet area: 1153 (107.12 sq.m.),3,3,1,Prayer Room,"155 Sector G-11, Islamabad, Pakistan",1 of 8 Floors,East,10+ Year Old,"['Police Station', 'Hospital', 'Bus Stop']",3 BHK Flat in G-11 located in G-11 Residency. ...,"['Modular Kitchen', 'No Fridge', 'No AC', 'Gey...","['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",3.0 ★,9996510.0,1153,8670.0,1.00

In [20]:
#df['price_per_sqft'].value_counts()

In [21]:

# bedrooms
df['bedRoom'].value_counts()

bedRoom
3    1199
2     807
1     675
4     318
5       1
Name: count, dtype: int64

In [22]:
df['bathroom'].isnull().sum()

0

In [23]:
df['balcony'].isnull().sum()

0

In [24]:
df['additionalRoom'].value_counts()

additionalRoom
Study Room      621
Servant Room    598
Prayer Room     593
Store Room      585
Name: count, dtype: int64

In [25]:
df['additionalRoom'].isnull().sum()

603

In [26]:
df['additionalRoom'].fillna('Not Available',inplace = True)

C:\Users\SAEEDCOMPUTERS\AppData\Local\Temp\ipykernel_1684\3574224523.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['additionalRoom'].fillna('Not Available',inplace = True)

In [27]:
#df['floorNum']

In [28]:
df['floorNum'].isnull().sum()

0

In [29]:
df['floorNum'] = df['floorNum'].str.split(' ').str.get(0).replace('Ground','0').str.replace('Basement','-1').str.replace('Lower','0').str.extract(r'(\d+)')

In [30]:
#df['floorNum']

In [31]:

# facing
df['facing'].value_counts()

facing
South-West    405
South         398
North         392
North-East    368
East          366
West          363
South-East    357
North-West    351
Name: count, dtype: int64

In [32]:
df['facing'].isnull().sum()

0

In [33]:
df.insert(loc=1,column='property_type',value='flat')

In [34]:
df.insert(loc=4,column='area',value=round((df['price_in_crore']*10000000)/df['price_per_sqft']))

In [83]:
df.head()

,property_name,property_type,society,areaWithType,area,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,price_per_sqft,price_in_crore
0,3 BHK Flat in DHA Phase 3,flat,DHA Phase 3 Residency,Carpet area: 1098 (102.01 sq.m.),1096.0,3,4,0,Study Room,"280 Street DHA Phase 3, Islamabad, Pakistan",2,East,Ready to Move,"['Supermarket', 'Bus Stop', 'Hospital', 'Polic...",3 BHK Flat in DHA Phase 3 located in DHA Phase...,"['Curtains', 'AC', 'TV', 'Modular Kitchen', 'S...","['CCTV', 'Park', 'Lift(s)', 'Power Back-up', '...",3.3 ★,18979.0,2.08
1,2 BHK Flat in G-14,flat,G-14 Residency,Carpet area: 844 (78.41 sq.m.),843.0,2,2,1,Servant Room,"184 Phase G-14, Islamabad, Pakistan",1,South,10+ Year Old,"['Supermarket', 'Police Station', 'Hospital', ...",2 BHK Flat in G-14 located in G-14 Residency. ...,"['TV', 'Fridge']","['Visitor Parking', 'Gym', 'Security Personnel...",4.7 ★,12580.0,1.06
2,4 BHK Flat in F-8,flat,F-8 Apartments,Carpet area: 1531 (142.23 sq.m.),1531.0,4,3,1,Study Room,"108 Phase F-8, Islamabad, Pakistan",6,East,5 to 10 Year Old,"['Bus Stop', 'MetroBus Station']",4 BHK Flat in F-8 located in F-8 Apartments. A...,"['No Fridge', 'Modular Kitchen', 'Geyser', 'Di...","['Gym', 'Visitor Parking', 'Lift(s)', 'Securit...",4.7 ★,39398.0,6.03
3,3 BHK Flat in G-10,flat,G-10 Homes,Carpet area: 1206 (112.04 sq.m.),1209.0,3,3,0,Servant Room,"203 Sector G-10, Islamabad, Pakistan",12,North-West,1 to 5 Year Old,"['School', 'MetroBus Station', 'Park']",3 BHK Flat in G-10 located in G-10 Homes. Appr...,"['TV', 'Fridge', 'Curtains', 'Sofa', 'No Fridg...","['Swimming Pool', '24/7 Water Supply', 'Commun...",3.4 ★,13818.0,1.67
4,3 BHK Flat in F-7,flat,F-7 Homes,Carpet area: 996 (92.53 sq.m.),995.0,3,3,0,Servant Room,"240 Phase F-7, Islamabad, Pakistan",14,South,10+ Year Old,"['Hospital', 'Mosque']",3 BHK Flat in F-7 located in F-7 Homes. Approx...,"['No AC', 'Washing Machine', 'Wardrobe', 'Frid...","['Swimming Pool', 'Community Center', 'Lift(s)...",4.2 ★,25824.0,2.57

In [36]:
df.drop(columns=['price_num','area_num'], inplace=True)

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3000 non-null   object
 1   property_type    3000 non-null   object
 2   society          3000 non-null   object
 3   areaWithType     3000 non-null   object
 4   area             3000 non-null   float64
 5   bedRoom          3000 non-null   int64
 6   bathroom         3000 non-null   int64
 7   balcony          3000 non-null   int64
 8   additionalRoom   3000 non-null   object
 9   address          3000 non-null   object
 10  floorNum         3000 non-null   object
 11  facing           3000 non-null   object
 12  agePossession    3000 non-null   object
 13  nearbyLocations  3000 non-null   object
 14  description      3000 non-null   object
 15  furnishDetails   3000 non-null   object
 16  features         3000 non-null   object
 17  rating           3000 non-null   object
 18  price_per_sqft   3000 non-null   float64
 19  price_in_crore   3000 non-null   float64
dtypes: float64(3), int64(3), object(14)
memory usage: 468.9+ KB

In [38]:
df.shape

(3000, 20)

In [39]:
df.to_csv('flats_cleaned.csv',index = False)