In [1]:
import numpy as np
import pandas as pd

In [2]:

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:

df = pd.read_csv('houses.csv')
df.sample(5)

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,description,furnishDetails,features,rating,property_id,nearbyLocations
988,6 Bedroom House in G-12,https://www.zameen.com/6-bedroom-independent-h...,G-12 Residency,"25,816,231 PKR","₹ 9,709/sq.ft.",2659,Built Up area: 2659 (247.03 sq.m.),6,5,3,Servant Room,"House No 852, Sector G-12, Islamabad, Pakistan",1,South-East,10+ Year Old,6 Bedroom House in G-12 located in G-12 Reside...,"['Modular Kitchen', 'TV', 'Curtains', 'Washing...","['Swimming Pool', 'Gym', 'CCTV', 'Security Per...",4.4 ★,ISB_H000989,"['School', 'Police Station']"
29,5 Bedroom House in DHA Phase 3,https://www.zameen.com/5-bedroom-independent-h...,DHA Phase 3 Residency,"34,459,992 PKR","₹ 13,419/sq.ft.",2568,Built Up area: 2568 (238.57 sq.m.),5,3,0,Pooja Room,"House No 314, Phase DHA Phase 3, Islamabad, Pa...",2,South-East,Ready to Move,5 Bedroom House in DHA Phase 3 located in DHA ...,"['Curtains', 'No Wardrobe', 'No AC', 'AC', 'Wa...","['Security Personnel', 'CCTV', 'Swimming Pool']",3.9 ★,ISB_H000030,"['MetroBus Station', 'Bus Stop', 'Shopping Mal..."
721,2 Bedroom House in F-8,https://www.zameen.com/2-bedroom-independent-h...,F-8 Enclave,"32,142,600 PKR","₹ 45,918/sq.ft.",700,Built Up area: 700 (65.03 sq.m.),2,1,1,Store Room,"House No 850, Phase F-8, Islamabad, Pakistan",5,South-East,Ready to Move,2 Bedroom House in F-8 located in F-8 Enclave....,"['Washing Machine', 'No Wardrobe', 'No Fridge'...","['Piped-gas', 'Security Personnel']",4.7 ★,ISB_H000722,"['Shopping Mall', 'University']"
818,5 Bedroom House in G-11,https://www.zameen.com/5-bedroom-independent-h...,G-11 Gardens,"17,943,513 PKR","₹ 13,461/sq.ft.",1333,Built Up area: 1333 (123.84 sq.m.),5,3,2,Pooja Room,"House No 635, Phase G-11, Islamabad, Pakistan",1,South-East,5 to 10 Year Old,5 Bedroom House in G-11 located in G-11 Garden...,"['No Wardrobe', 'AC', 'Modular Kitchen']","['Private Garden / Terrace', 'Piped-gas', 'Swi...",4.8 ★,ISB_H000819,"['Hospital', 'Shopping Mall', 'Police Station'..."
1038,6 Bedroom House in DHA Phase 2,https://www.zameen.com/6-bedroom-independent-h...,DHA Phase 2 Gardens,"26,301,905 PKR","₹ 15,989/sq.ft.",1645,Built Up area: 1645 (152.83 sq.m.),6,4,1,Store Room,"House No 598, Street DHA Phase 2, Islamabad, P...",1,North-West,Ready to Move,6 Bedroom House in DHA Phase 2 located in DHA ...,"['No Wardrobe', 'No Fridge', 'Washing Machine'...","['Water Storage', 'CCTV', 'Gym', 'Power Back-u...",3.8 ★,ISB_H001039,"['Mosque', 'Hospital', 'MetroBus Station', 'Po..."

In [4]:
df.shape

(1054, 21)

In [5]:

# info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054 entries, 0 to 1053
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1054 non-null   object
 1   link             1054 non-null   object
 2   society          1054 non-null   object
 3   price            1054 non-null   object
 4   rate             1054 non-null   object
 5   area             1054 non-null   int64
 6   areaWithType     1054 non-null   object
 7   bedRoom          1054 non-null   int64
 8   bathroom         1054 non-null   int64
 9   balcony          1054 non-null   int64
 10  additionalRoom   875 non-null    object
 11  address          1054 non-null   object
 12  noOfFloor        1054 non-null   int64
 13  facing           1054 non-null   object
 14  agePossession    1054 non-null   object
 15  description      1054 non-null   object
 16  furnishDetails   1054 non-null   object
 17  features         1054 non-null   object
 18  rating           1054 non-null   object
 19  property_id      1054 non-null   object
 20  nearbyLocations  1054 non-null   object
dtypes: int64(5), object(16)
memory usage: 173.1+ KB

In [6]:
df.duplicated().sum()

0

In [7]:
df.isnull().sum()

property_name        0
link                 0
society              0
price                0
rate                 0
area                 0
areaWithType         0
bedRoom              0
bathroom             0
balcony              0
additionalRoom     179
address              0
noOfFloor            0
facing               0
agePossession        0
description          0
furnishDetails       0
features             0
rating               0
property_id          0
nearbyLocations      0
dtype: int64

In [8]:

# Columns to drop -> property_name, link, property_id
df.drop(columns=['link','property_id'], inplace=True)

In [9]:

df.head()

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,description,furnishDetails,features,rating,nearbyLocations
0,6 Bedroom House in F-6,F-6 Enclave,"73,386,941 PKR","₹ 45,953/sq.ft.",1597,Built Up area: 1597 (148.37 sq.m.),6,6,1,Store Room,"House No 693, Street F-6, Islamabad, Pakistan",2,East,Ready to Move,6 Bedroom House in F-6 located in F-6 Enclave....,"['No Wardrobe', 'Modular Kitchen', 'Geyser', '...","['CCTV', 'Visitor Parking', 'Independent Parki...",3.3 ★,"['Market', 'Bus Stop', 'Hospital', 'Mosque', '..."
1,5 Bedroom House in G-15,G-15 Enclave,"25,933,214 PKR","₹ 15,871/sq.ft.",1634,Built Up area: 1634 (151.8 sq.m.),5,3,1,Pooja Room,"House No 95, Sector G-15, Islamabad, Pakistan",2,West,5 to 10 Year Old,5 Bedroom House in G-15 located in G-15 Enclav...,"['TV', 'Modular Kitchen', 'No AC', 'No Wardrob...","['Piped-gas', 'Independent Parking']",4.7 ★,"['Shopping Mall', 'Bus Stop']"
2,6 Bedroom House in Sadiqabad,Sadiqabad Residency,"32,077,869 PKR","₹ 11,789/sq.ft.",2721,Built Up area: 2721 (252.79 sq.m.),6,4,0,Servant Room,"House No 888, Street Sadiqabad, Islamabad, Pak...",2,North-East,0 to 1 Year Old,6 Bedroom House in Sadiqabad located in Sadiqa...,"['Geyser', 'TV', 'Wardrobe', 'No Fridge']","['Piped-gas', 'CCTV', 'Power Back-up']",4.7 ★,"['Park', 'Mosque', 'Shopping Mall', 'Hospital'..."
3,7 Bedroom House in DHA Phase 3,DHA Phase 3 Enclave,"30,124,809 PKR","₹ 12,727/sq.ft.",2367,Built Up area: 2367 (219.9 sq.m.),7,5,3,Store Room,"House No 825, Phase DHA Phase 3, Islamabad, Pa...",3,North,1 to 5 Year Old,7 Bedroom House in DHA Phase 3 located in DHA ...,"['Geyser', 'No AC', 'Washing Machine', 'Curtai...","['Power Back-up', 'Independent Parking', 'Wate...",3.4 ★,"['Park', 'Hospital', 'University', 'Bus Stop',..."
4,6 Bedroom House in Sadiqabad,Sadiqabad Residency,"10,676,646 PKR","₹ 7,038/sq.ft.",1517,Built Up area: 1517 (140.93 sq.m.),6,5,3,Study Room,"House No 142, Sector Sadiqabad, Islamabad, Pak...",5,South-East,5 to 10 Year Old,6 Bedroom House in Sadiqabad located in Sadiqa...,"['AC', 'Washing Machine', 'Wardrobe']","['Gym', 'Visitor Parking', 'Independent Parkin...",4.2 ★,"['Market', 'Hospital']"

In [10]:
# rename columns
df.rename(columns={'rate':'price_per_sqft'},inplace=True)
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,description,furnishDetails,features,rating,nearbyLocations
0,6 Bedroom House in F-6,F-6 Enclave,"73,386,941 PKR","₹ 45,953/sq.ft.",1597,Built Up area: 1597 (148.37 sq.m.),6,6,1,Store Room,"House No 693, Street F-6, Islamabad, Pakistan",2,East,Ready to Move,6 Bedroom House in F-6 located in F-6 Enclave....,"['No Wardrobe', 'Modular Kitchen', 'Geyser', '...","['CCTV', 'Visitor Parking', 'Independent Parki...",3.3 ★,"['Market', 'Bus Stop', 'Hospital', 'Mosque', '..."
1,5 Bedroom House in G-15,G-15 Enclave,"25,933,214 PKR","₹ 15,871/sq.ft.",1634,Built Up area: 1634 (151.8 sq.m.),5,3,1,Pooja Room,"House No 95, Sector G-15, Islamabad, Pakistan",2,West,5 to 10 Year Old,5 Bedroom House in G-15 located in G-15 Enclav...,"['TV', 'Modular Kitchen', 'No AC', 'No Wardrob...","['Piped-gas', 'Independent Parking']",4.7 ★,"['Shopping Mall', 'Bus Stop']"
2,6 Bedroom House in Sadiqabad,Sadiqabad Residency,"32,077,869 PKR","₹ 11,789/sq.ft.",2721,Built Up area: 2721 (252.79 sq.m.),6,4,0,Servant Room,"House No 888, Street Sadiqabad, Islamabad, Pak...",2,North-East,0 to 1 Year Old,6 Bedroom House in Sadiqabad located in Sadiqa...,"['Geyser', 'TV', 'Wardrobe', 'No Fridge']","['Piped-gas', 'CCTV', 'Power Back-up']",4.7 ★,"['Park', 'Mosque', 'Shopping Mall', 'Hospital'..."
3,7 Bedroom House in DHA Phase 3,DHA Phase 3 Enclave,"30,124,809 PKR","₹ 12,727/sq.ft.",2367,Built Up area: 2367 (219.9 sq.m.),7,5,3,Store Room,"House No 825, Phase DHA Phase 3, Islamabad, Pa...",3,North,1 to 5 Year Old,7 Bedroom House in DHA Phase 3 located in DHA ...,"['Geyser', 'No AC', 'Washing Machine', 'Curtai...","['Power Back-up', 'Independent Parking', 'Wate...",3.4 ★,"['Park', 'Hospital', 'University', 'Bus Stop',..."
4,6 Bedroom House in Sadiqabad,Sadiqabad Residency,"10,676,646 PKR","₹ 7,038/sq.ft.",1517,Built Up area: 1517 (140.93 sq.m.),6,5,3,Study Room,"House No 142, Sector Sadiqabad, Islamabad, Pak...",5,South-East,5 to 10 Year Old,6 Bedroom House in Sadiqabad located in Sadiqa...,"['AC', 'Washing Machine', 'Wardrobe']","['Gym', 'Visitor Parking', 'Independent Parkin...",4.2 ★,"['Market', 'Hospital']"

In [11]:
# society
df['society'].value_counts()

society
Margalla Hills Enclave        21
Rawalpindi Cantt Heights      19
Chaklala Heights              16
Chaklala Enclave              16
DHA Phase 3 Residency         15
G-9 Villas                    14
DHA Phase 2 Villas            13
Rawalpindi Cantt Gardens      13
I-8 Villas                    13
Gulzar-e-Quaid Enclave        13
G-12 Residency                12
Sadiqabad Enclave             12
Gulzar-e-Quaid Villas         12
G-12 Villas                   12
G-6 Residency                 12
DHA Phase 2 Heights           12
DHA Phase 2 Residency         12
DHA Phase 1 Heights           12
F-7 Gardens                   12
Gulzar-e-Quaid Gardens        11
Bahria Town Enclave           11
Gulzar-e-Quaid Residency      11
G-15 Heights                  11
G-11 Enclave                  11
DHA Phase 3 Gardens           11
I-8 Residency                 11
E-11 Gardens                  10
Rawalpindi Cantt Villas       10
F-8 Enclave                   10
G-10 Heights                  10
G-9 Residency                 10
I-8 Gardens                   10
Margalla Hills Gardens        10
F-8 Residency                 10
E-7 Heights                   10
G-13 Residency                10
F-10 Enclave                  10
Gulzar-e-Quaid Heights        10
F-11 Enclave                   9
Sadiqabad Gardens              9
Bahria Town Heights            9
E-11 Enclave                   9
G-6 Gardens                    9
F-11 Villas                    9
Chaklala Residency             9
I-8 Heights                    9
F-5 Heights                    9
Bahria Town Residency          9
G-14 Gardens                   9
F-7 Enclave                    9
DHA Phase 3 Villas             9
DHA Phase 1 Residency          9
DHA Phase 3 Enclave            9
G-11 Residency                 9
Bahria Town Villas             9
G-13 Gardens                   8
F-11 Gardens                   8
G-6 Heights                    8
G-9 Enclave                    8
G-13 Heights                   8
G-15 Enclave                   8
E-11 Villas                    8
G-11 Gardens                   8
F-11 Residency                 8
F-11 Heights                   8
F-5 Villas                     8
DHA Phase 3 Heights            8
Sadiqabad Heights              7
DHA Phase 1 Enclave            7
F-8 Gardens                    7
Sadiqabad Residency            7
I-8 Enclave                    7
Margalla Hills Residency       7
F-6 Enclave                    7
DHA Phase 2 Enclave            7
G-9 Heights                    7
E-11 Residency                 7
Margalla Hills Villas          7
F-8 Heights                    7
Rawalpindi Cantt Residency     7
DHA Phase 1 Villas             7
E-11 Heights                   7
G-14 Heights                   7
G-14 Enclave                   6
G-13 Villas                    6
Bahria Town Gardens            6
F-7 Heights                    6
F-7 Villas                     6
F-5 Enclave                    6
G-11 Heights                   6
G-15 Villas                    6
Sadiqabad Villas               6
Chaklala Villas                6
F-10 Heights                   6
F-6 Gardens                    6
G-9 Gardens                    6
G-10 Residency                 6
Rawalpindi Cantt Enclave       6
F-10 Residency                 6
Chaklala Gardens               6
F-5 Gardens                    6
G-6 Enclave                    6
E-7 Villas                     5
G-10 Villas                    5
G-10 Enclave                   5
G-12 Heights                   5
DHA Phase 1 Gardens            5
F-8 Villas                     5
G-12 Enclave                   5
F-10 Gardens                   5
Margalla Hills Heights         5
G-14 Residency                 5
G-6 Villas                     5
E-7 Enclave                    5
F-6 Villas                     5
G-15 Gardens                   5
G-10 Gardens                   5
F-7 Residency                  5
G-15 Residency                 4
F-6 Residency                  4
G-11 Villas                    4
F-5 Residency                  4
E-7 Residency                  4
DHA Phase 2 Gardens            4
G-14 Villas                    4
G-12 Gardens                   4
F-6 Heights                    3
F-10 Villas                    3
G-13 Enclave                   2
E-7 Gardens                    1
Name: count, dtype: int64

In [12]:
import re
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [13]:
df['society'].value_counts().shape

(130,)

In [14]:
df['society'] = df['society'].str.replace('nan','independent')

In [15]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,description,furnishDetails,features,rating,nearbyLocations
0,6 Bedroom House in F-6,f-6 enclave,"73,386,941 PKR","₹ 45,953/sq.ft.",1597,Built Up area: 1597 (148.37 sq.m.),6,6,1,Store Room,"House No 693, Street F-6, Islamabad, Pakistan",2,East,Ready to Move,6 Bedroom House in F-6 located in F-6 Enclave....,"['No Wardrobe', 'Modular Kitchen', 'Geyser', '...","['CCTV', 'Visitor Parking', 'Independent Parki...",3.3 ★,"['Market', 'Bus Stop', 'Hospital', 'Mosque', '..."
1,5 Bedroom House in G-15,g-15 enclave,"25,933,214 PKR","₹ 15,871/sq.ft.",1634,Built Up area: 1634 (151.8 sq.m.),5,3,1,Pooja Room,"House No 95, Sector G-15, Islamabad, Pakistan",2,West,5 to 10 Year Old,5 Bedroom House in G-15 located in G-15 Enclav...,"['TV', 'Modular Kitchen', 'No AC', 'No Wardrob...","['Piped-gas', 'Independent Parking']",4.7 ★,"['Shopping Mall', 'Bus Stop']"
2,6 Bedroom House in Sadiqabad,sadiqabad residency,"32,077,869 PKR","₹ 11,789/sq.ft.",2721,Built Up area: 2721 (252.79 sq.m.),6,4,0,Servant Room,"House No 888, Street Sadiqabad, Islamabad, Pak...",2,North-East,0 to 1 Year Old,6 Bedroom House in Sadiqabad located in Sadiqa...,"['Geyser', 'TV', 'Wardrobe', 'No Fridge']","['Piped-gas', 'CCTV', 'Power Back-up']",4.7 ★,"['Park', 'Mosque', 'Shopping Mall', 'Hospital'..."
3,7 Bedroom House in DHA Phase 3,dha phase 3 enclave,"30,124,809 PKR","₹ 12,727/sq.ft.",2367,Built Up area: 2367 (219.9 sq.m.),7,5,3,Store Room,"House No 825, Phase DHA Phase 3, Islamabad, Pa...",3,North,1 to 5 Year Old,7 Bedroom House in DHA Phase 3 located in DHA ...,"['Geyser', 'No AC', 'Washing Machine', 'Curtai...","['Power Back-up', 'Independent Parking', 'Wate...",3.4 ★,"['Park', 'Hospital', 'University', 'Bus Stop',..."
4,6 Bedroom House in Sadiqabad,sadiqabad residency,"10,676,646 PKR","₹ 7,038/sq.ft.",1517,Built Up area: 1517 (140.93 sq.m.),6,5,3,Study Room,"House No 142, Sector Sadiqabad, Islamabad, Pak...",5,South-East,5 to 10 Year Old,6 Bedroom House in Sadiqabad located in Sadiqa...,"['AC', 'Washing Machine', 'Wardrobe']","['Gym', 'Visitor Parking', 'Independent Parkin...",4.2 ★,"['Market', 'Hospital']"

In [16]:
#df['price'].value_counts()

In [17]:
def convert_price_to_crore(price_str):
    import re
    
    # Ensure it's a string
    price_str = str(price_str)
    
    # Extract only digits
    numeric = re.sub(r'[^\d]', '', price_str)
    
    if not numeric:
        return None
    
    value = float(numeric)
    return round(value / 10000000, 2)
df['price_in_crore'] = df['price'].apply(convert_price_to_crore)

In [18]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,description,furnishDetails,features,rating,nearbyLocations,price_in_crore
0,6 Bedroom House in F-6,f-6 enclave,"73,386,941 PKR","₹ 45,953/sq.ft.",1597,Built Up area: 1597 (148.37 sq.m.),6,6,1,Store Room,"House No 693, Street F-6, Islamabad, Pakistan",2,East,Ready to Move,6 Bedroom House in F-6 located in F-6 Enclave....,"['No Wardrobe', 'Modular Kitchen', 'Geyser', '...","['CCTV', 'Visitor Parking', 'Independent Parki...",3.3 ★,"['Market', 'Bus Stop', 'Hospital', 'Mosque', '...",7.34
1,5 Bedroom House in G-15,g-15 enclave,"25,933,214 PKR","₹ 15,871/sq.ft.",1634,Built Up area: 1634 (151.8 sq.m.),5,3,1,Pooja Room,"House No 95, Sector G-15, Islamabad, Pakistan",2,West,5 to 10 Year Old,5 Bedroom House in G-15 located in G-15 Enclav...,"['TV', 'Modular Kitchen', 'No AC', 'No Wardrob...","['Piped-gas', 'Independent Parking']",4.7 ★,"['Shopping Mall', 'Bus Stop']",2.59
2,6 Bedroom House in Sadiqabad,sadiqabad residency,"32,077,869 PKR","₹ 11,789/sq.ft.",2721,Built Up area: 2721 (252.79 sq.m.),6,4,0,Servant Room,"House No 888, Street Sadiqabad, Islamabad, Pak...",2,North-East,0 to 1 Year Old,6 Bedroom House in Sadiqabad located in Sadiqa...,"['Geyser', 'TV', 'Wardrobe', 'No Fridge']","['Piped-gas', 'CCTV', 'Power Back-up']",4.7 ★,"['Park', 'Mosque', 'Shopping Mall', 'Hospital'...",3.21
3,7 Bedroom House in DHA Phase 3,dha phase 3 enclave,"30,124,809 PKR","₹ 12,727/sq.ft.",2367,Built Up area: 2367 (219.9 sq.m.),7,5,3,Store Room,"House No 825, Phase DHA Phase 3, Islamabad, Pa...",3,North,1 to 5 Year Old,7 Bedroom House in DHA Phase 3 located in DHA ...,"['Geyser', 'No AC', 'Washing Machine', 'Curtai...","['Power Back-up', 'Independent Parking', 'Wate...",3.4 ★,"['Park', 'Hospital', 'University', 'Bus Stop',...",3.01
4,6 Bedroom House in Sadiqabad,sadiqabad residency,"10,676,646 PKR","₹ 7,038/sq.ft.",1517,Built Up area: 1517 (140.93 sq.m.),6,5,3,Study Room,"House No 142, Sector Sadiqabad, Islamabad, Pak...",5,South-East,5 to 10 Year Old,6 Bedroom House in Sadiqabad located in Sadiqa...,"['AC', 'Washing Machine', 'Wardrobe']","['Gym', 'Visitor Parking', 'Independent Parkin...",4.2 ★,"['Market', 'Hospital']",1.07

In [19]:
df.drop(columns=['price'], inplace=True)

In [20]:
#df['price_per_sqft'].value_counts()

In [21]:
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹','').str.replace(',','').str.strip().astype('float')

In [22]:
df.head()

,property_name,society,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,description,furnishDetails,features,rating,nearbyLocations,price_in_crore
0,6 Bedroom House in F-6,f-6 enclave,45953.0,1597,Built Up area: 1597 (148.37 sq.m.),6,6,1,Store Room,"House No 693, Street F-6, Islamabad, Pakistan",2,East,Ready to Move,6 Bedroom House in F-6 located in F-6 Enclave....,"['No Wardrobe', 'Modular Kitchen', 'Geyser', '...","['CCTV', 'Visitor Parking', 'Independent Parki...",3.3 ★,"['Market', 'Bus Stop', 'Hospital', 'Mosque', '...",7.34
1,5 Bedroom House in G-15,g-15 enclave,15871.0,1634,Built Up area: 1634 (151.8 sq.m.),5,3,1,Pooja Room,"House No 95, Sector G-15, Islamabad, Pakistan",2,West,5 to 10 Year Old,5 Bedroom House in G-15 located in G-15 Enclav...,"['TV', 'Modular Kitchen', 'No AC', 'No Wardrob...","['Piped-gas', 'Independent Parking']",4.7 ★,"['Shopping Mall', 'Bus Stop']",2.59
2,6 Bedroom House in Sadiqabad,sadiqabad residency,11789.0,2721,Built Up area: 2721 (252.79 sq.m.),6,4,0,Servant Room,"House No 888, Street Sadiqabad, Islamabad, Pak...",2,North-East,0 to 1 Year Old,6 Bedroom House in Sadiqabad located in Sadiqa...,"['Geyser', 'TV', 'Wardrobe', 'No Fridge']","['Piped-gas', 'CCTV', 'Power Back-up']",4.7 ★,"['Park', 'Mosque', 'Shopping Mall', 'Hospital'...",3.21
3,7 Bedroom House in DHA Phase 3,dha phase 3 enclave,12727.0,2367,Built Up area: 2367 (219.9 sq.m.),7,5,3,Store Room,"House No 825, Phase DHA Phase 3, Islamabad, Pa...",3,North,1 to 5 Year Old,7 Bedroom House in DHA Phase 3 located in DHA ...,"['Geyser', 'No AC', 'Washing Machine', 'Curtai...","['Power Back-up', 'Independent Parking', 'Wate...",3.4 ★,"['Park', 'Hospital', 'University', 'Bus Stop',...",3.01
4,6 Bedroom House in Sadiqabad,sadiqabad residency,7038.0,1517,Built Up area: 1517 (140.93 sq.m.),6,5,3,Study Room,"House No 142, Sector Sadiqabad, Islamabad, Pak...",5,South-East,5 to 10 Year Old,6 Bedroom House in Sadiqabad located in Sadiqa...,"['AC', 'Washing Machine', 'Wardrobe']","['Gym', 'Visitor Parking', 'Independent Parkin...",4.2 ★,"['Market', 'Hospital']",1.07

In [23]:
df['bedRoom'].value_counts()

bedRoom
5     247
4     202
6     186
3     182
2      80
8      73
7      65
12      5
16      5
10      5
9       4
Name: count, dtype: int64

In [24]:
df[df['bedRoom'].isnull()]

Empty DataFrame
Columns: [property_name, society, price_per_sqft, area, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, noOfFloor, facing, agePossession, description, furnishDetails, features, rating, nearbyLocations, price_in_crore]
Index: []

In [25]:
df = df[~df['bedRoom'].isnull()]

In [26]:
df.shape

(1054, 19)

In [27]:
 #additionalRoom
df['additionalRoom'].value_counts()

additionalRoom
Store Room      188
Study Room      177
Pooja Room      171
Servant Room    171
Prayer Room     168
Name: count, dtype: int64

In [28]:
df['additionalRoom'].fillna('Not Available',inplace=True)

C:\Users\SAEEDCOMPUTERS\AppData\Local\Temp\ipykernel_13512\3934844758.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['additionalRoom'].fillna('Not Available',inplace=True)

In [29]:
df.sample(5)

,property_name,society,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,description,furnishDetails,features,rating,nearbyLocations,price_in_crore
869,5 Bedroom House in DHA Phase 1,dha phase 1 residency,20593.0,2555,Built Up area: 2555 (237.37 sq.m.),5,5,0,Store Room,"House No 304, Block DHA Phase 1, Islamabad, Pa...",5,North-West,0 to 1 Year Old,5 Bedroom House in DHA Phase 1 located in DHA ...,"['Geyser', 'No Wardrobe']","['Visitor Parking', 'Independent Parking', 'Po...",4.2 ★,"['Police Station', 'School', 'MetroBus Station']",5.26
672,5 Bedroom House in G-12,g-12 villas,12287.0,1229,Built Up area: 1229 (114.18 sq.m.),5,5,2,Prayer Room,"House No 821, Phase G-12, Islamabad, Pakistan",4,North,Under Construction,5 Bedroom House in G-12 located in G-12 Villas...,"['Geyser', 'No Wardrobe', 'No AC']","['Security Personnel', 'Piped-gas', 'Swimming ...",4.0 ★,"['School', 'MetroBus Station']",1.51
1010,4 Bedroom House in F-7,f-7 heights,57757.0,1548,Built Up area: 1548 (143.81 sq.m.),4,4,2,Pooja Room,"House No 932, Phase F-7, Islamabad, Pakistan",2,North,1 to 5 Year Old,4 Bedroom House in F-7 located in F-7 Heights....,"['Modular Kitchen', 'AC', 'TV', 'Wardrobe', 'G...","['Power Back-up', 'Independent Parking', 'Priv...",4.3 ★,"['Police Station', 'Market', 'University', 'Pa...",8.94
459,4 Bedroom House in F-7,f-7 enclave,45937.0,1045,Built Up area: 1045 (97.08 sq.m.),4,3,1,Not Available,"House No 535, Block F-7, Islamabad, Pakistan",4,South-West,Ready to Move,4 Bedroom House in F-7 located in F-7 Enclave....,"['Geyser', 'Wardrobe', 'TV', 'Washing Machine'...","['Swimming Pool', 'Piped-gas']",4.5 ★,"['Mosque', 'Park', 'Shopping Mall', 'Police St...",4.80
829,2 Bedroom House in E-7,e-7 villas,48589.0,700,Built Up area: 700 (65.03 sq.m.),2,2,2,Pooja Room,"House No 474, Sector E-7, Islamabad, Pakistan",3,East,0 to 1 Year Old,2 Bedroom House in E-7 located in E-7 Villas. ...,"['No AC', 'Wardrobe']","['Swimming Pool', 'Power Back-up']",3.1 ★,"['Bus Stop', 'School']",3.40

In [30]:
df['noOfFloor'].value_counts()

noOfFloor
2    245
3    208
5    203
1    199
4    199
Name: count, dtype: int64

In [31]:
df['noOfFloor'].isnull().sum()

0

In [32]:
df.rename(columns={'noOfFloor':'floorNum'},inplace=True)

In [33]:
df.head()

,property_name,society,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,description,furnishDetails,features,rating,nearbyLocations,price_in_crore
0,6 Bedroom House in F-6,f-6 enclave,45953.0,1597,Built Up area: 1597 (148.37 sq.m.),6,6,1,Store Room,"House No 693, Street F-6, Islamabad, Pakistan",2,East,Ready to Move,6 Bedroom House in F-6 located in F-6 Enclave....,"['No Wardrobe', 'Modular Kitchen', 'Geyser', '...","['CCTV', 'Visitor Parking', 'Independent Parki...",3.3 ★,"['Market', 'Bus Stop', 'Hospital', 'Mosque', '...",7.34
1,5 Bedroom House in G-15,g-15 enclave,15871.0,1634,Built Up area: 1634 (151.8 sq.m.),5,3,1,Pooja Room,"House No 95, Sector G-15, Islamabad, Pakistan",2,West,5 to 10 Year Old,5 Bedroom House in G-15 located in G-15 Enclav...,"['TV', 'Modular Kitchen', 'No AC', 'No Wardrob...","['Piped-gas', 'Independent Parking']",4.7 ★,"['Shopping Mall', 'Bus Stop']",2.59
2,6 Bedroom House in Sadiqabad,sadiqabad residency,11789.0,2721,Built Up area: 2721 (252.79 sq.m.),6,4,0,Servant Room,"House No 888, Street Sadiqabad, Islamabad, Pak...",2,North-East,0 to 1 Year Old,6 Bedroom House in Sadiqabad located in Sadiqa...,"['Geyser', 'TV', 'Wardrobe', 'No Fridge']","['Piped-gas', 'CCTV', 'Power Back-up']",4.7 ★,"['Park', 'Mosque', 'Shopping Mall', 'Hospital'...",3.21
3,7 Bedroom House in DHA Phase 3,dha phase 3 enclave,12727.0,2367,Built Up area: 2367 (219.9 sq.m.),7,5,3,Store Room,"House No 825, Phase DHA Phase 3, Islamabad, Pa...",3,North,1 to 5 Year Old,7 Bedroom House in DHA Phase 3 located in DHA ...,"['Geyser', 'No AC', 'Washing Machine', 'Curtai...","['Power Back-up', 'Independent Parking', 'Wate...",3.4 ★,"['Park', 'Hospital', 'University', 'Bus Stop',...",3.01
4,6 Bedroom House in Sadiqabad,sadiqabad residency,7038.0,1517,Built Up area: 1517 (140.93 sq.m.),6,5,3,Study Room,"House No 142, Sector Sadiqabad, Islamabad, Pak...",5,South-East,5 to 10 Year Old,6 Bedroom House in Sadiqabad located in Sadiqa...,"['AC', 'Washing Machine', 'Wardrobe']","['Gym', 'Visitor Parking', 'Independent Parkin...",4.2 ★,"['Market', 'Hospital']",1.07

In [34]:
df['facing'].fillna('NA',inplace=True)

C:\Users\SAEEDCOMPUTERS\AppData\Local\Temp\ipykernel_13512\3692945726.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['facing'].fillna('NA',inplace=True)

In [35]:
df['area'] = round((df['price_in_crore']*10000000)/df['price_per_sqft'])

In [36]:
df.insert(loc=1,column='property_type',value='house')

In [37]:
df.head()

,property_name,property_type,society,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,description,furnishDetails,features,rating,nearbyLocations,price_in_crore
0,6 Bedroom House in F-6,house,f-6 enclave,45953.0,1597.0,Built Up area: 1597 (148.37 sq.m.),6,6,1,Store Room,"House No 693, Street F-6, Islamabad, Pakistan",2,East,Ready to Move,6 Bedroom House in F-6 located in F-6 Enclave....,"['No Wardrobe', 'Modular Kitchen', 'Geyser', '...","['CCTV', 'Visitor Parking', 'Independent Parki...",3.3 ★,"['Market', 'Bus Stop', 'Hospital', 'Mosque', '...",7.34
1,5 Bedroom House in G-15,house,g-15 enclave,15871.0,1632.0,Built Up area: 1634 (151.8 sq.m.),5,3,1,Pooja Room,"House No 95, Sector G-15, Islamabad, Pakistan",2,West,5 to 10 Year Old,5 Bedroom House in G-15 located in G-15 Enclav...,"['TV', 'Modular Kitchen', 'No AC', 'No Wardrob...","['Piped-gas', 'Independent Parking']",4.7 ★,"['Shopping Mall', 'Bus Stop']",2.59
2,6 Bedroom House in Sadiqabad,house,sadiqabad residency,11789.0,2723.0,Built Up area: 2721 (252.79 sq.m.),6,4,0,Servant Room,"House No 888, Street Sadiqabad, Islamabad, Pak...",2,North-East,0 to 1 Year Old,6 Bedroom House in Sadiqabad located in Sadiqa...,"['Geyser', 'TV', 'Wardrobe', 'No Fridge']","['Piped-gas', 'CCTV', 'Power Back-up']",4.7 ★,"['Park', 'Mosque', 'Shopping Mall', 'Hospital'...",3.21
3,7 Bedroom House in DHA Phase 3,house,dha phase 3 enclave,12727.0,2365.0,Built Up area: 2367 (219.9 sq.m.),7,5,3,Store Room,"House No 825, Phase DHA Phase 3, Islamabad, Pa...",3,North,1 to 5 Year Old,7 Bedroom House in DHA Phase 3 located in DHA ...,"['Geyser', 'No AC', 'Washing Machine', 'Curtai...","['Power Back-up', 'Independent Parking', 'Wate...",3.4 ★,"['Park', 'Hospital', 'University', 'Bus Stop',...",3.01
4,6 Bedroom House in Sadiqabad,house,sadiqabad residency,7038.0,1520.0,Built Up area: 1517 (140.93 sq.m.),6,5,3,Study Room,"House No 142, Sector Sadiqabad, Islamabad, Pak...",5,South-East,5 to 10 Year Old,6 Bedroom House in Sadiqabad located in Sadiqa...,"['AC', 'Washing Machine', 'Wardrobe']","['Gym', 'Visitor Parking', 'Independent Parkin...",4.2 ★,"['Market', 'Hospital']",1.07

In [38]:
cols = list(df.columns)

# current index of price_per_sqft
pps_index = cols.index('price_per_sqft')

# remove both columns first
cols.remove('price_per_sqft')
cols.remove('areaWithType')

# insert areaWithType where price_per_sqft was originally
cols.insert(pps_index, 'areaWithType')

# insert price_per_sqft at 2nd last position
cols.insert(len(cols), 'price_per_sqft')   # this puts it last
cols.insert(len(cols)-1, cols.pop())       # this moves it to 2nd last

# apply new column order
df = df[cols]

In [39]:
df.head()

,property_name,property_type,society,areaWithType,area,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,description,furnishDetails,features,rating,nearbyLocations,price_in_crore,price_per_sqft
0,6 Bedroom House in F-6,house,f-6 enclave,Built Up area: 1597 (148.37 sq.m.),1597.0,6,6,1,Store Room,"House No 693, Street F-6, Islamabad, Pakistan",2,East,Ready to Move,6 Bedroom House in F-6 located in F-6 Enclave....,"['No Wardrobe', 'Modular Kitchen', 'Geyser', '...","['CCTV', 'Visitor Parking', 'Independent Parki...",3.3 ★,"['Market', 'Bus Stop', 'Hospital', 'Mosque', '...",7.34,45953.0
1,5 Bedroom House in G-15,house,g-15 enclave,Built Up area: 1634 (151.8 sq.m.),1632.0,5,3,1,Pooja Room,"House No 95, Sector G-15, Islamabad, Pakistan",2,West,5 to 10 Year Old,5 Bedroom House in G-15 located in G-15 Enclav...,"['TV', 'Modular Kitchen', 'No AC', 'No Wardrob...","['Piped-gas', 'Independent Parking']",4.7 ★,"['Shopping Mall', 'Bus Stop']",2.59,15871.0
2,6 Bedroom House in Sadiqabad,house,sadiqabad residency,Built Up area: 2721 (252.79 sq.m.),2723.0,6,4,0,Servant Room,"House No 888, Street Sadiqabad, Islamabad, Pak...",2,North-East,0 to 1 Year Old,6 Bedroom House in Sadiqabad located in Sadiqa...,"['Geyser', 'TV', 'Wardrobe', 'No Fridge']","['Piped-gas', 'CCTV', 'Power Back-up']",4.7 ★,"['Park', 'Mosque', 'Shopping Mall', 'Hospital'...",3.21,11789.0
3,7 Bedroom House in DHA Phase 3,house,dha phase 3 enclave,Built Up area: 2367 (219.9 sq.m.),2365.0,7,5,3,Store Room,"House No 825, Phase DHA Phase 3, Islamabad, Pa...",3,North,1 to 5 Year Old,7 Bedroom House in DHA Phase 3 located in DHA ...,"['Geyser', 'No AC', 'Washing Machine', 'Curtai...","['Power Back-up', 'Independent Parking', 'Wate...",3.4 ★,"['Park', 'Hospital', 'University', 'Bus Stop',...",3.01,12727.0
4,6 Bedroom House in Sadiqabad,house,sadiqabad residency,Built Up area: 1517 (140.93 sq.m.),1520.0,6,5,3,Study Room,"House No 142, Sector Sadiqabad, Islamabad, Pak...",5,South-East,5 to 10 Year Old,6 Bedroom House in Sadiqabad located in Sadiqa...,"['AC', 'Washing Machine', 'Wardrobe']","['Gym', 'Visitor Parking', 'Independent Parkin...",4.2 ★,"['Market', 'Hospital']",1.07,7038.0

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054 entries, 0 to 1053
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1054 non-null   object
 1   property_type    1054 non-null   object
 2   society          1054 non-null   object
 3   areaWithType     1054 non-null   object
 4   area             1054 non-null   float64
 5   bedRoom          1054 non-null   int64
 6   bathroom         1054 non-null   int64
 7   balcony          1054 non-null   int64
 8   additionalRoom   1054 non-null   object
 9   address          1054 non-null   object
 10  floorNum         1054 non-null   int64
 11  facing           1054 non-null   object
 12  agePossession    1054 non-null   object
 13  description      1054 non-null   object
 14  furnishDetails   1054 non-null   object
 15  features         1054 non-null   object
 16  rating           1054 non-null   object
 17  nearbyLocations  1054 non-null   object
 18  price_in_crore   1054 non-null   float64
 19  price_per_sqft   1054 non-null   float64
dtypes: float64(3), int64(4), object(13)
memory usage: 164.8+ KB

In [41]:
# Clean column names (remove leading/trailing spaces)
# Remove leading/trailing spaces from column names
df.columns = df.columns.str.strip()

cols = list(df.columns)

# get current indexes
idx_desc = cols.index("description")
idx_near = cols.index("nearbyLocations")

# swap the two columns
cols[idx_desc], cols[idx_near] = cols[idx_near], cols[idx_desc]

# apply new order to df
df = df[cols]

In [89]:
# Remove leading/trailing spaces from column names
df.columns = df.columns.str.strip()

cols = list(df.columns)

# find indexes
idx_desc = cols.index("description")
idx_furnish = cols.index("furnishDetails")

# swap the two columns
cols[idx_desc], cols[idx_furnish] = cols[idx_furnish], cols[idx_desc]

# apply new order
df = df[cols]

In [93]:
# Remove leading/trailing spaces from column names
df.columns = df.columns.str.strip()

cols = list(df.columns)

# find indexes
idx_furnish = cols.index("furnishDetails")
idx_features = cols.index("features")

# swap the two columns
cols[idx_furnish], cols[idx_features] = cols[idx_features], cols[idx_furnish]

# apply new order
df = df[cols]

In [95]:
# Clean column names (remove extra spaces)
df.columns = df.columns.str.strip()

cols = list(df.columns)

# find indexes
idx_rating = cols.index("rating")
idx_features = cols.index("features")

# swap the positions
cols[idx_rating], cols[idx_features] = cols[idx_features], cols[idx_rating]

# apply new column order
df = df[cols]

In [99]:
# Clean column names (remove extra spaces)
df.columns = df.columns.str.strip()

cols = list(df.columns)

# find indexes
idx_sqft = cols.index("price_per_sqft")
idx_crore = cols.index("price_in_crore")

# swap the positions
cols[idx_sqft], cols[idx_crore] = cols[idx_crore], cols[idx_sqft]

# apply new order
df = df[cols]

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054 entries, 0 to 1053
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1054 non-null   object
 1   property_type    1054 non-null   object
 2   society          1054 non-null   object
 3   areaWithType     1054 non-null   object
 4   area             1054 non-null   float64
 5   bedRoom          1054 non-null   int64
 6   bathroom         1054 non-null   int64
 7   balcony          1054 non-null   int64
 8   additionalRoom   1054 non-null   object
 9   address          1054 non-null   object
 10  floorNum         1054 non-null   int64
 11  facing           1054 non-null   object
 12  agePossession    1054 non-null   object
 13  nearbyLocations  1054 non-null   object
 14  description      1054 non-null   object
 15  furnishDetails   1054 non-null   object
 16  features         1054 non-null   object
 17  rating           1054 non-null   object
 18  price_per_sqft   1054 non-null   float64
 19  price_in_crore   1054 non-null   float64
dtypes: float64(3), int64(4), object(13)
memory usage: 164.8+ KB

In [103]:
df.head()

,property_name,property_type,society,areaWithType,area,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,price_per_sqft,price_in_crore
0,6 Bedroom House in F-6,house,f-6 enclave,Built Up area: 1597 (148.37 sq.m.),1597.0,6,6,1,Store Room,"House No 693, Street F-6, Islamabad, Pakistan",2,East,Ready to Move,"['Market', 'Bus Stop', 'Hospital', 'Mosque', '...",6 Bedroom House in F-6 located in F-6 Enclave....,"['No Wardrobe', 'Modular Kitchen', 'Geyser', '...","['CCTV', 'Visitor Parking', 'Independent Parki...",3.3 ★,45953.0,7.34
1,5 Bedroom House in G-15,house,g-15 enclave,Built Up area: 1634 (151.8 sq.m.),1632.0,5,3,1,Pooja Room,"House No 95, Sector G-15, Islamabad, Pakistan",2,West,5 to 10 Year Old,"['Shopping Mall', 'Bus Stop']",5 Bedroom House in G-15 located in G-15 Enclav...,"['TV', 'Modular Kitchen', 'No AC', 'No Wardrob...","['Piped-gas', 'Independent Parking']",4.7 ★,15871.0,2.59
2,6 Bedroom House in Sadiqabad,house,sadiqabad residency,Built Up area: 2721 (252.79 sq.m.),2723.0,6,4,0,Servant Room,"House No 888, Street Sadiqabad, Islamabad, Pak...",2,North-East,0 to 1 Year Old,"['Park', 'Mosque', 'Shopping Mall', 'Hospital'...",6 Bedroom House in Sadiqabad located in Sadiqa...,"['Geyser', 'TV', 'Wardrobe', 'No Fridge']","['Piped-gas', 'CCTV', 'Power Back-up']",4.7 ★,11789.0,3.21
3,7 Bedroom House in DHA Phase 3,house,dha phase 3 enclave,Built Up area: 2367 (219.9 sq.m.),2365.0,7,5,3,Store Room,"House No 825, Phase DHA Phase 3, Islamabad, Pa...",3,North,1 to 5 Year Old,"['Park', 'Hospital', 'University', 'Bus Stop',...",7 Bedroom House in DHA Phase 3 located in DHA ...,"['Geyser', 'No AC', 'Washing Machine', 'Curtai...","['Power Back-up', 'Independent Parking', 'Wate...",3.4 ★,12727.0,3.01
4,6 Bedroom House in Sadiqabad,house,sadiqabad residency,Built Up area: 1517 (140.93 sq.m.),1520.0,6,5,3,Study Room,"House No 142, Sector Sadiqabad, Islamabad, Pak...",5,South-East,5 to 10 Year Old,"['Market', 'Hospital']",6 Bedroom House in Sadiqabad located in Sadiqa...,"['AC', 'Washing Machine', 'Wardrobe']","['Gym', 'Visitor Parking', 'Independent Parkin...",4.2 ★,7038.0,1.07

In [105]:
df.to_csv('house_cleaned.csv',index=False)