In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [3]:
df = pd.read_csv('Islamabad_properties.csv')

In [4]:
df.sample(5)

,property_name,property_type,society,areaWithType,area,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,price_per_sqft,price_in_crore
1929,4 Bedroom House in Bahria Town,house,bahria town heights,Built Up area: 1655 (153.75 sq.m.),1658.0,4,4,0,Store Room,"House No 41, Block Bahria Town, Islamabad, Pak...",5,East,1 to 5 Year Old,"['School', 'Park']",4 Bedroom House in Bahria Town located in Bahr...,"['No Fridge', 'Washing Machine', 'Modular Kitc...","['Security Personnel', 'CCTV', 'Visitor Parkin...",3.1 ★,15985.0,2.65
106,4 BHK Flat in Bahria Town,flat,Bahria Town Homes,Carpet area: 1452 (134.9 sq.m.),1455.0,4,3,1,Study Room,"265 Street Bahria Town, Islamabad, Pakistan",1,South-West,1 to 5 Year Old,"['Mosque', 'Hospital']",4 BHK Flat in Bahria Town located in Bahria To...,"['Dining Table', 'Wardrobe', 'Geyser', 'AC']","['Visitor Parking', 'Lift(s)']",4.8 ★,12989.0,1.89
3154,1 BHK Flat in G-15,flat,G-15 Plaza,Carpet area: 350 (32.52 sq.m.),351.0,1,1,0,Study Room,"206 Sector G-15, Islamabad, Pakistan",5,South,Under Construction,"['Hospital', 'University']",1 BHK Flat in G-15 located in G-15 Plaza. Appr...,"['TV', 'Curtains', 'AC', 'Wardrobe', 'Dining T...","['Community Center', 'Swimming Pool', 'CCTV', ...",4.4 ★,19397.0,0.68
3445,5 Bedroom House in DHA Phase 2,house,dha phase 2 enclave,Built Up area: 2565 (238.3 sq.m.),2564.0,5,5,3,Study Room,"House No 327, Phase DHA Phase 2, Islamabad, Pa...",1,South-West,0 to 1 Year Old,"['Bus Stop', 'Park']",5 Bedroom House in DHA Phase 2 located in DHA ...,"['No AC', 'Curtains', 'No Wardrobe', 'AC']","['Independent Parking', 'Visitor Parking', 'Sw...",4.9 ★,21415.0,5.49
2359,1 BHK Flat in DHA Phase 3,flat,DHA Phase 3 Homes,Carpet area: 350 (32.52 sq.m.),350.0,1,1,0,Not Available,"221 Block DHA Phase 3, Islamabad, Pakistan",0,North-West,5 to 10 Year Old,"['Bus Stop', 'University', 'Hospital']",1 BHK Flat in DHA Phase 3 located in DHA Phase...,"['Sofa', 'Geyser', 'Wardrobe', 'Washing Machin...","['Park', '24/7 Water Supply', 'Power Back-up',...",3.8 ★,23440.0,0.82

In [5]:
df.shape

(4054, 20)

In [6]:
df.duplicated().sum()

0

In [7]:
df.isnull().sum()

property_name      0
property_type      0
society            0
areaWithType       0
area               0
bedRoom            0
bathroom           0
balcony            0
additionalRoom     0
address            0
floorNum           0
facing             0
agePossession      0
nearbyLocations    0
description        0
furnishDetails     0
features           0
rating             0
price_per_sqft     0
price_in_crore     0
dtype: int64

In [8]:
df.insert(loc = 3 , column = 'location',value =
          df['property_name'].str.split('in').str.get(1).
              str.replace('Islamabad','').
              str.strip())

In [9]:
# df['property_name'].str.split('in').str.get(1).str.replace('Islamabad','').  str.strip()

In [10]:
df.head()

,property_name,property_type,society,location,areaWithType,area,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,price_per_sqft,price_in_crore
0,2 BHK Flat in DHA Phase 1,flat,DHA Phase 1 Apartments,DHA Phase 1,Carpet area: 791 (73.49 sq.m.),793.0,2,2,1,Prayer Room,"161 Street DHA Phase 1, Islamabad, Pakistan",3,North-East,5 to 10 Year Old,"['Shopping Mall', 'Bus Stop']",2 BHK Flat in DHA Phase 1 located in DHA Phase...,"['Geyser', 'Curtains', 'Dining Table', 'Modula...","['Swimming Pool', 'Security Personnel']",3.3 ★,23596.0,1.87
1,2 BHK Flat in G-15,flat,G-15 Residency,G-15,Carpet area: 870 (80.83 sq.m.),870.0,2,2,3,Study Room,"172 Block G-15, Islamabad, Pakistan",3,East,0 to 1 Year Old,"['Bus Stop', 'Shopping Mall', 'University', 'M...",2 BHK Flat in G-15 located in G-15 Residency. ...,"['Wardrobe', 'No Fridge', 'Sofa']","['Lift(s)', 'CCTV', 'Power Back-up', 'Security...",4.7 ★,21505.0,1.87
2,3 BHK Flat in Bahria Town,flat,Bahria Town Heights,Bahria Town,Carpet area: 946 (87.89 sq.m.),947.0,3,3,2,Store Room,"64 Phase Bahria Town, Islamabad, Pakistan",6,South,Under Construction,"['Supermarket', 'Park', 'Police Station', 'Sch...",3 BHK Flat in Bahria Town located in Bahria To...,"['AC', 'Modular Kitchen', 'Washing Machine', '...","['24/7 Water Supply', 'Visitor Parking']",3.2 ★,19433.0,1.84
3,3 BHK Flat in G-12,flat,G-12 Homes,G-12,Carpet area: 1321 (122.72 sq.m.),1322.0,3,4,3,Prayer Room,"23 Sector G-12, Islamabad, Pakistan",9,North,10+ Year Old,"['School', 'Supermarket', 'University', 'Shopp...",3 BHK Flat in G-12 located in G-12 Homes. Appr...,"['Washing Machine', 'Modular Kitchen']","['CCTV', 'Visitor Parking']",4.8 ★,14069.0,1.86
4,1 BHK Flat in G-12,flat,G-12 Plaza,G-12,Carpet area: 354 (32.89 sq.m.),356.0,1,1,1,Study Room,"195 Street G-12, Islamabad, Pakistan",1,West,5 to 10 Year Old,"['Bus Stop', 'Park', 'Police Station', 'Superm...",1 BHK Flat in G-12 located in G-12 Plaza. Appr...,"['Geyser', 'Dining Table', 'No Fridge', 'Modul...","['Power Back-up', 'Park', 'Gym']",4.9 ★,14319.0,0.51

In [11]:
df['location'].value_counts()

location
I-8               198
G-12              192
G-10              184
Margalla Hills    184
E-11              184
DHA Phase 1       182
G-6               181
Bahria Town       178
F-11              177
G-14              175
G-9               175
F-8               174
F-5               174
G-11              173
DHA Phase 3       171
G-15              169
F-7               169
DHA Phase 2       165
G-13              165
F-10              161
E-7               160
F-6               157
Gulzar-e-Quaid     57
Rawalp             55
Chaklala           53
Sadiqabad          41
Name: count, dtype: int64

In [12]:
df.drop(columns = ['property_name','address','description','rating'],inplace = True)

In [13]:
df.head()

,property_type,society,location,areaWithType,area,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features,price_per_sqft,price_in_crore
0,flat,DHA Phase 1 Apartments,DHA Phase 1,Carpet area: 791 (73.49 sq.m.),793.0,2,2,1,Prayer Room,3,North-East,5 to 10 Year Old,"['Shopping Mall', 'Bus Stop']","['Geyser', 'Curtains', 'Dining Table', 'Modula...","['Swimming Pool', 'Security Personnel']",23596.0,1.87
1,flat,G-15 Residency,G-15,Carpet area: 870 (80.83 sq.m.),870.0,2,2,3,Study Room,3,East,0 to 1 Year Old,"['Bus Stop', 'Shopping Mall', 'University', 'M...","['Wardrobe', 'No Fridge', 'Sofa']","['Lift(s)', 'CCTV', 'Power Back-up', 'Security...",21505.0,1.87
2,flat,Bahria Town Heights,Bahria Town,Carpet area: 946 (87.89 sq.m.),947.0,3,3,2,Store Room,6,South,Under Construction,"['Supermarket', 'Park', 'Police Station', 'Sch...","['AC', 'Modular Kitchen', 'Washing Machine', '...","['24/7 Water Supply', 'Visitor Parking']",19433.0,1.84
3,flat,G-12 Homes,G-12,Carpet area: 1321 (122.72 sq.m.),1322.0,3,4,3,Prayer Room,9,North,10+ Year Old,"['School', 'Supermarket', 'University', 'Shopp...","['Washing Machine', 'Modular Kitchen']","['CCTV', 'Visitor Parking']",14069.0,1.86
4,flat,G-12 Plaza,G-12,Carpet area: 354 (32.89 sq.m.),356.0,1,1,1,Study Room,1,West,5 to 10 Year Old,"['Bus Stop', 'Park', 'Police Station', 'Superm...","['Geyser', 'Dining Table', 'No Fridge', 'Modul...","['Power Back-up', 'Park', 'Gym']",14319.0,0.51

In [28]:
df.to_csv('Islamabad_properties_cleaned_v1.csv',index = False)