In [1]:
import pandas as pd
import re 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
df = pd.read_excel('Islamabad_Apartments_250_Final.xlsx')

In [3]:
df.head()

,PropertyName,PropertySubName,LocationAdvantages,Link,PriceDetails,TopFacilities
0,Bahria Town - G-6 - Unit 1,1 BHK Apartment in Bahria Town,"G-6 | Bahria Town Markets, Express Highway Acc...",https://www.zameen.com/Flats_Apartments/Islama...,"5.86 Crore | 550 sqft | Monthly Rent: PKR 24,971","[Playground, Green Area, Basketball Court]"
1,Chaklala - Block B - Unit 2,2 BHK Apartment in Chaklala,"Block B | Old Rawalpindi Area, Close to Canton...",https://www.zameen.com/Flats_Apartments/Islama...,"8.91 Crore | 1120 sqft | Monthly Rent: PKR 51,309","[Generator Backup, 24/7 Security, Lifts]"
2,DHA Phase 1 - Street 1 - Unit 3,3 BHK Apartment in DHA Phase 1,"Street 1 | DHA Main Gate, Shopping Malls, Park...",https://www.zameen.com/Flats_Apartments/Islama...,18.85 Crore | 1600 sqft | Monthly Rent: PKR 67...,"[Swimming Pool, Gym, Security, Parking]"
3,DHA Phase 2 - Street 10 - Unit 4,4 BHK Apartment in DHA Phase 2,"Street 10 | Centaurus Mall, Serena Hotel, Conv...",https://www.zameen.com/Flats_Apartments/Islama...,20.54 Crore | 2000 sqft | Monthly Rent: PKR 95...,"[Rooftop Garden, Lounge Area, Restaurant]"
4,DHA Phase 3 - Street 5 - Unit 5,1 BHK Apartment in DHA Phase 3,"Street 5 | Golf Course, Shopping Area, Green S...",https://www.zameen.com/Flats_Apartments/Islama...,"5.37 Crore | 550 sqft | Monthly Rent: PKR 24,648","[Elevator, Security Gate, CCTV, Parking]"

In [4]:
df.shape

(250, 6)

In [5]:
df.sample()

,PropertyName,PropertySubName,LocationAdvantages,Link,PriceDetails,TopFacilities
154,Rawalpindi - PWD - Unit 155,3 BHK Apartment in Rawalpindi,"PWD | Twin Cities Center, Commercial Hub, Tran...",https://www.zameen.com/Flats_Apartments/Islama...,10.46 Crore | 1600 sqft | Monthly Rent: PKR 75...,"[Cafe, Salon, Clinic, Laundry Service]"

In [6]:
df.iloc[3].LocationAdvantages

'Street 10 | Centaurus Mall, Serena Hotel, Convention Center | Distance: 1-3 KM to main markets'

In [7]:
df.iloc[1].PriceDetails

'8.91 Crore | 1120 sqft | Monthly Rent: PKR 51,309'

In [8]:
df.head()

,PropertyName,PropertySubName,LocationAdvantages,Link,PriceDetails,TopFacilities
0,Bahria Town - G-6 - Unit 1,1 BHK Apartment in Bahria Town,"G-6 | Bahria Town Markets, Express Highway Acc...",https://www.zameen.com/Flats_Apartments/Islama...,"5.86 Crore | 550 sqft | Monthly Rent: PKR 24,971","[Playground, Green Area, Basketball Court]"
1,Chaklala - Block B - Unit 2,2 BHK Apartment in Chaklala,"Block B | Old Rawalpindi Area, Close to Canton...",https://www.zameen.com/Flats_Apartments/Islama...,"8.91 Crore | 1120 sqft | Monthly Rent: PKR 51,309","[Generator Backup, 24/7 Security, Lifts]"
2,DHA Phase 1 - Street 1 - Unit 3,3 BHK Apartment in DHA Phase 1,"Street 1 | DHA Main Gate, Shopping Malls, Park...",https://www.zameen.com/Flats_Apartments/Islama...,18.85 Crore | 1600 sqft | Monthly Rent: PKR 67...,"[Swimming Pool, Gym, Security, Parking]"
3,DHA Phase 2 - Street 10 - Unit 4,4 BHK Apartment in DHA Phase 2,"Street 10 | Centaurus Mall, Serena Hotel, Conv...",https://www.zameen.com/Flats_Apartments/Islama...,20.54 Crore | 2000 sqft | Monthly Rent: PKR 95...,"[Rooftop Garden, Lounge Area, Restaurant]"
4,DHA Phase 3 - Street 5 - Unit 5,1 BHK Apartment in DHA Phase 3,"Street 5 | Golf Course, Shopping Area, Green S...",https://www.zameen.com/Flats_Apartments/Islama...,"5.37 Crore | 550 sqft | Monthly Rent: PKR 24,648","[Elevator, Security Gate, CCTV, Parking]"

In [9]:

df.iloc[1].PriceDetails

'8.91 Crore | 1120 sqft | Monthly Rent: PKR 51,309'

In [10]:
def convert_to_crore(price_string):
    """Extract PKR amount and convert to Crore"""
    # Extract numeric values from the string
    numbers = re.findall(r'[\d,]+', price_string)
    
    if not numbers:
        return price_string
    
    # Get the first number (price in PKR)
    price_pkr = int(numbers[0].replace(',', ''))
    
    # Convert PKR to Crore (1 Crore = 10,000,000 PKR)
    price_crore = price_pkr / 10000000
    
    # Replace PKR amount with Crore amount
    updated_string = price_string.replace(numbers[0], f"{price_crore:.2f} Crore")
    
    return updated_string

# Apply the conversion function to PriceDetails column
df['PriceDetails'] = df['PriceDetails'].apply(convert_to_crore)

In [11]:
df.iloc[1].PriceDetails

'0.00 Crore.91 Crore | 1120 sqft | Monthly Rent: PKR 51,309'

In [12]:
df[['PropertyName','TopFacilities']]['TopFacilities'][0]

'[Playground, Green Area, Basketball Court]'

In [13]:
df.head()

,PropertyName,PropertySubName,LocationAdvantages,Link,PriceDetails,TopFacilities
0,Bahria Town - G-6 - Unit 1,1 BHK Apartment in Bahria Town,"G-6 | Bahria Town Markets, Express Highway Acc...",https://www.zameen.com/Flats_Apartments/Islama...,0.00 Crore.86 Crore | 0.00 Crore0.00 Crore0 sq...,"[Playground, Green Area, Basketball Court]"
1,Chaklala - Block B - Unit 2,2 BHK Apartment in Chaklala,"Block B | Old Rawalpindi Area, Close to Canton...",https://www.zameen.com/Flats_Apartments/Islama...,0.00 Crore.91 Crore | 1120 sqft | Monthly Rent...,"[Generator Backup, 24/7 Security, Lifts]"
2,DHA Phase 1 - Street 1 - Unit 3,3 BHK Apartment in DHA Phase 1,"Street 1 | DHA Main Gate, Shopping Malls, Park...",https://www.zameen.com/Flats_Apartments/Islama...,0.00 Crore.85 Crore | 1600 sqft | Monthly Rent...,"[Swimming Pool, Gym, Security, Parking]"
3,DHA Phase 2 - Street 10 - Unit 4,4 BHK Apartment in DHA Phase 2,"Street 10 | Centaurus Mall, Serena Hotel, Conv...",https://www.zameen.com/Flats_Apartments/Islama...,0.00 Crore.54 Crore | 0.00 Crore00 sqft | Mont...,"[Rooftop Garden, Lounge Area, Restaurant]"
4,DHA Phase 3 - Street 5 - Unit 5,1 BHK Apartment in DHA Phase 3,"Street 5 | Golf Course, Shopping Area, Green S...",https://www.zameen.com/Flats_Apartments/Islama...,0.00 Crore.37 Crore | 0.00 Crore0.00 Crore0 sq...,"[Elevator, Security Gate, CCTV, Parking]"

In [14]:
def convert_facilities_to_string(facilities):
    """Convert list format string to clean string"""
    # Remove brackets [ and ]
    facilities = facilities.replace('[', '').replace(']', '')
    
    # Remove quotes if any
    facilities = facilities.replace("'", "").replace('"', '')
    
    return facilities

# Apply conversion to TopFacilities column
df['FacilitiesStr'] = df['TopFacilities'].apply(convert_facilities_to_string)

In [15]:
df['FacilitiesStr'][0]

'Playground, Green Area, Basketball Court'

In [16]:
tfidf_vectorizer = TfidfVectorizer(stop_words='english', ngram_range=(1, 2))

In [17]:
tfidf_matrix = tfidf_vectorizer.fit_transform(df['FacilitiesStr'])

In [18]:
tfidf_matrix.toarray()[0]

array([0.        , 0.        , 0.        , 0.27600516, 0.33982002,
       0.        , 0.        , 0.        , 0.        , 0.33982002,
       0.33982002, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.33982002, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.33982002, 0.33982002, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.33982002, 0.33982002, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [41]:
cosine_sim1 = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [43]:
def recommend_properties(property_name, cosine_sim=cosine_sim1):
    # Get the index of the property that matches the name
    idx = df.index[df['PropertyName'] == property_name].tolist()[0]

    # Get the pairwise similarity scores with that property
    sim_scores = list(enumerate(cosine_sim1[idx]))

    # Sort the properties based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar properties
    sim_scores = sim_scores[1:6]

    # Get the property indices
    property_indices = [i[0] for i in sim_scores]
    
    recommendations_df = pd.DataFrame({
        'PropertyName': df['PropertyName'].iloc[property_indices],
        'SimilarityScore': sim_scores
    })

    # Return the top 10 most similar properties
    return recommendations_df

In [45]:
cosine_sim1.shape

(250, 250)

In [47]:
df[['PropertyName','PriceDetails']]['PriceDetails'][1]

'0.00 Crore.91 Crore | 1120 sqft | Monthly Rent: PKR 51,309'

In [ ]:
'''def recommend_properties(property_name, cosine_sim=cosine_sim):
    # Get the index of the property that matches the name
    idx = df.index[df['PropertyName'] == property_name].tolist()[0]

    # Get the pairwise similarity scores with that property
    sim_scores = list(enumerate(cosine_sim1[idx]))

    # Sort the properties based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar properties
    sim_scores = sim_scores[1:6]

    # Get the property indices
    property_indices = [i[0] for i in sim_scores]
    
    recommendations_df = pd.DataFrame({
        'PropertyName': df['PropertyName'].iloc[property_indices],
        'SimilarityScore': sim_scores
    })

    # Return the top 10 most similar properties
    return recommendations_df'''

In [50]:
recommend_properties("Bahria Town - G-6 - Unit 1")

                          PropertyName           SimilarityScore
9   Margalla Hills - Central - Unit 10   (9, 1.0000000000000002)
13        Chaklala - Block C - Unit 14  (13, 1.0000000000000002)
24        Bahria Town - F-10 - Unit 25  (24, 1.0000000000000002)
33    Margalla Hills - South - Unit 34  (33, 1.0000000000000002)
52   DHA Phase 3 - Street 10 - Unit 53  (52, 1.0000000000000002)

In [52]:
df[['PropertyName','PriceDetails']]['PriceDetails'][1]

'0.00 Crore.91 Crore | 1120 sqft | Monthly Rent: PKR 51,309'

In [54]:
import pandas as pd
import json
import re

# Load the dataset
df_apartments = pd.read_excel('Islamabad_Apartments_250_Final.xlsx')

# Function to parse PriceDetails and extract features
def parse_price_details(detail_str):
    """
    Parse price details string and extract building type, area, and price
    Format: "4.50 Crore | 1000 sqft | Monthly Rent: PKR 45,000"
    """
    try:
        extracted = {}
        
        # Extract price in Crore
        price_match = re.search(r'([\d.]+)\s*Crore', detail_str)
        if price_match:
            price = float(price_match.group(1))
            extracted['price'] = price
        
        # Extract area in sqft
        area_match = re.search(r'(\d+)\s*sqft', detail_str)
        if area_match:
            area = float(area_match.group(1))
            extracted['area'] = area
        
        return extracted
    except:
        return {}

# Function to get building type from PropertySubName
def get_building_type(subname):
    """Extract BHK type and building type from PropertySubName"""
    bhk_match = re.search(r'(\d+)\s*BHK', subname)
    if bhk_match:
        bhk = f"{bhk_match.group(1)} BHK"
    else:
        bhk = None
    
    building_type = None
    if 'Apartment' in subname:
        building_type = 'Apartment'
    elif 'Villa' in subname:
        building_type = 'Villa'
    elif 'Floor' in subname:
        building_type = 'Independent Floor'
    
    return bhk, building_type

# Extract location from PropertyName (sirf pehla part)
def extract_location(property_name):
    """Extract location name - sirf pehla part dashes sai pehle"""
    return property_name.split(' - ')[0].strip()

# Transform the dataset
data_refined = []

for idx, row in df_apartments.iterrows():
    # Extract location name (sirf location, baki details remove)
    location = extract_location(row['PropertyName'])
    
    # Extract BHK type and building type
    bhk, building_type = get_building_type(row['PropertySubName'])
    
    # Parse price details
    price_data = parse_price_details(row['PriceDetails'])
    
    # Create base row with location instead of full PropertyName
    new_row = {
        'PropertyName': location,  # Sirf location name - column name same
        'PropertySubName': row['PropertySubName'],
        'LocationAdvantages': row['LocationAdvantages'],
        'TopFacilities': row['TopFacilities'],
        'Link': row['Link']
    }
    
    # Add building type, area, and price for all BHK configurations
    for config in ['1 BHK', '2 BHK', '3 BHK', '4 BHK', '5 BHK', '6 BHK', '1 RK', 'Land']:
        # Set building type only for matching BHK
        if bhk == config:
            new_row[f'building_type_{config}'] = building_type
            new_row[f'area_low_{config}'] = price_data.get('area')
            new_row[f'area_high_{config}'] = price_data.get('area')
            new_row[f'price_low_{config}'] = price_data.get('price')
            new_row[f'price_high_{config}'] = price_data.get('price')
        else:
            new_row[f'building_type_{config}'] = None
            new_row[f'area_low_{config}'] = None
            new_row[f'area_high_{config}'] = None
            new_row[f'price_low_{config}'] = None
            new_row[f'price_high_{config}'] = None
    
    data_refined.append(new_row)

# Create the final refined dataframe
df_final_refined = pd.DataFrame(data_refined)

# Set Location as index
df_final_refined_indexed = df_final_refined.set_index('PropertyName')

# Fill empty building type columns with location name
print("--- Filling empty building type columns with location names ---")
building_cols = [col for col in df_final_refined.columns if 'building_type_' in col]
for col in building_cols:
    building_name = col.replace('building_type_', '')
    # Fillna aur empty strings ko location name se replace karo
    df_final_refined_indexed[col] = df_final_refined_indexed[col].fillna(building_name).replace('', building_name)
    print(f"✓ {col} -> filled with location-based building type")

# Display sample
print("\n✓ Dataset Transformation Complete!\n")
print("Sample data (first 5 rows):")
print(df_final_refined_indexed.head())
print(f"\n✓ Total rows: {len(df_final_refined_indexed)}")
print(f"✓ Total columns: {len(df_final_refined_indexed.columns)}")

# Save to Excel
df_final_refined_indexed.to_excel('Islamabad_Apartments_Transformed_Indexed.xlsx')
print("\n✓ File saved as 'Islamabad_Apartments_Transformed_Indexed.xlsx' (Location as index)")

# Save to CSV
df_final_refined.to_csv('Islamabad_Apartments_Transformed.csv', index=False)
print("✓ File saved as 'Islamabad_Apartments_Transformed.csv'")

# Display column breakdown
print("\n--- Column Structure ---")
print("Base columns: PropertyName, PropertySubName, LocationAdvantages, TopFacilities, Link")
print("\nFor each BHK type (1 BHK, 2 BHK, 3 BHK, 4 BHK, 5 BHK, 6 BHK, 1 RK, Land):")
print("  - building_type_{BHK}")
print("  - area_low_{BHK}")
print("  - area_high_{BHK}")
print("  - price_low_{BHK} (in Crore)")
print("  - price_high_{BHK} (in Crore)")

df_final_refined_v2 = df_final_refined_indexed

--- Filling empty building type columns with location names ---
✓ building_type_1 BHK -> filled with location-based building type
✓ building_type_2 BHK -> filled with location-based building type
✓ building_type_3 BHK -> filled with location-based building type
✓ building_type_4 BHK -> filled with location-based building type
✓ building_type_5 BHK -> filled with location-based building type
✓ building_type_6 BHK -> filled with location-based building type
✓ building_type_1 RK -> filled with location-based building type
✓ building_type_Land -> filled with location-based building type

✓ Dataset Transformation Complete!

Sample data (first 5 rows):
                             PropertySubName  \
PropertyName
Bahria Town   1 BHK Apartment in Bahria Town
Chaklala         2 BHK Apartment in Chaklala
DHA Phase 1   3 BHK Apartment in DHA Phase 1
DHA Phase 2   4 BHK Apartment in DHA Phase 2
DHA Phase 3   1 BHK Apartment in DHA Phase 3

                                             LocationAdvantages  \
PropertyName
Bahria Town   G-6 | Bahria Town Markets, Express Highway Acc...
Chaklala      Block B | Old Rawalpindi Area, Close to Canton...
DHA Phase 1   Street 1 | DHA Main Gate, Shopping Malls, Park...
DHA Phase 2   Street 10 | Centaurus Mall, Serena Hotel, Conv...
DHA Phase 3   Street 5 | Golf Course, Shopping Area, Green S...

                                           TopFacilities  \
PropertyName
Bahria Town   [Playground, Green Area, Basketball Court]
Chaklala        [Generator Backup, 24/7 Security, Lifts]
DHA Phase 1      [Swimming Pool, Gym, Security, Parking]
DHA Phase 2    [Rooftop Garden, Lounge Area, Restaurant]
DHA Phase 3     [Elevator, Security Gate, CCTV, Parking]

                                                           Link  \
PropertyName
Bahria Town   https://www.zameen.com/Flats_Apartments/Islama...
Chaklala      https://www.zameen.com/Flats_Apartments/Islama...
DHA Phase 1   https://www.zameen.com/Flats_Apartments/Islama...
DHA Phase 2   https://www.zameen.com/Flats_Apartments/Islama...
DHA Phase 3   https://www.zameen.com/Flats_Apartments/Islama...

             building_type_1 BHK  area_low_1 BHK  area_high_1 BHK  \
PropertyName
Bahria Town            Apartment           550.0            550.0
Chaklala                   1 BHK             NaN              NaN
DHA Phase 1                1 BHK             NaN              NaN
DHA Phase 2                1 BHK             NaN              NaN
DHA Phase 3            Apartment           550.0            550.0

              price_low_1 BHK  price_high_1 BHK building_type_2 BHK  ...  \
PropertyName                                                         ...
Bahria Town              5.86              5.86               2 BHK  ...
Chaklala                  NaN               NaN           Apartment  ...
DHA Phase 1               NaN               NaN               2 BHK  ...
DHA Phase 2               NaN               NaN               2 BHK  ...
DHA Phase 3              5.37              5.37               2 BHK  ...

              building_type_1 RK  area_low_1 RK  area_high_1 RK  \
PropertyName
Bahria Town                 1 RK           None            None
Chaklala                    1 RK           None            None
DHA Phase 1                 1 RK           None            None
DHA Phase 2                 1 RK           None            None
DHA Phase 3                 1 RK           None            None

              price_low_1 RK price_high_1 RK  building_type_Land  \
PropertyName
Bahria Town             None            None                Land
Chaklala                None            None                Land
DHA Phase 1             None            None                Land
DHA Phase 2             None            None                Land
DHA Phase 3             None            None                Land

              area_low_Land  area_high_Land  price_low_Land price_high_Land
PropertyName
Bahria Town            None            None            None            None
Chaklala               None            None            None            None
DHA Phase 1            None            None            None            None
DHA Phase 2            None            None            None            None
DHA Phase 3            None            None            None            None

[5 rows x 44 columns]

✓ Total rows: 250
✓ Total columns: 44

✓ File saved as 'Islamabad_Apartments_Transformed_Indexed.xlsx' (Location as index)
✓ File saved as 'Islamabad_Apartments_Transformed.csv'

--- Column Structure ---
Base columns: PropertyName, PropertySubName, LocationAdvantages, TopFacilities, Link

For each BHK type (1 BHK, 2 BHK, 3 BHK, 4 BHK, 5 BHK, 6 BHK, 1 RK, Land):
  - building_type_{BHK}
  - area_low_{BHK}
  - area_high_{BHK}
  - price_low_{BHK} (in Crore)
  - price_high_{BHK} (in Crore)

In [56]:
import pandas as pd

# First, check what columns actually exist
print("All columns in dataframe:")
print(df_final_refined_v2.columns.tolist())
print("\n")

# Check if 'building type_Land' exists
if 'building type_Land' in df_final_refined_v2.columns:
    print("✓ Column exists!")
    df_final_refined_v2['building type_Land'] = df_final_refined_v2['building type_Land'].replace('', 'Land')
else:
    print("✗ Column 'building type_Land' NOT found!")
    print("\nSimilar columns with 'Land':")
    land_cols = [col for col in df_final_refined_v2.columns if 'Land' in col]
    print(land_cols)
    
    if land_cols:
        # Use the actual column name
        actual_col = land_cols[0]
        print(f"\nUsing column: '{actual_col}'")
        df_final_refined_v2[actual_col] = df_final_refined_v2[actual_col].fillna('Land').replace('', 'Land')
        print(f"✓ Replaced empty values in '{actual_col}' with 'Land'")

print("\n--- Checking all building type columns ---")
building_cols = [col for col in df_final_refined_v2.columns if 'building' in col.lower()]
print(building_cols)

# Replace empty strings with building type name for ALL building type columns
print("\nReplacing empty values in all building type columns...")
for col in building_cols:
    # Extract the type (e.g., 'Land' from 'building type_Land')
    building_name = col.replace('building type_', '').replace('building_type_', '')
    
    df_final_refined_v2[col] = df_final_refined_v2[col].fillna(building_name).replace('', building_name)
    print(f"✓ {col} -> replaced with '{building_name}'")

print("\n✓ All building type columns updated!")
print("\nSample data:")
print(df_final_refined_v2[building_cols].head())

# Save the updated dataframe

All columns in dataframe:
['PropertySubName', 'LocationAdvantages', 'TopFacilities', 'Link', 'building_type_1 BHK', 'area_low_1 BHK', 'area_high_1 BHK', 'price_low_1 BHK', 'price_high_1 BHK', 'building_type_2 BHK', 'area_low_2 BHK', 'area_high_2 BHK', 'price_low_2 BHK', 'price_high_2 BHK', 'building_type_3 BHK', 'area_low_3 BHK', 'area_high_3 BHK', 'price_low_3 BHK', 'price_high_3 BHK', 'building_type_4 BHK', 'area_low_4 BHK', 'area_high_4 BHK', 'price_low_4 BHK', 'price_high_4 BHK', 'building_type_5 BHK', 'area_low_5 BHK', 'area_high_5 BHK', 'price_low_5 BHK', 'price_high_5 BHK', 'building_type_6 BHK', 'area_low_6 BHK', 'area_high_6 BHK', 'price_low_6 BHK', 'price_high_6 BHK', 'building_type_1 RK', 'area_low_1 RK', 'area_high_1 RK', 'price_low_1 RK', 'price_high_1 RK', 'building_type_Land', 'area_low_Land', 'area_high_Land', 'price_low_Land', 'price_high_Land']


✗ Column 'building type_Land' NOT found!

Similar columns with 'Land':
['building_type_Land', 'area_low_Land', 'area_high_Land', 'price_low_Land', 'price_high_Land']

Using column: 'building_type_Land'
✓ Replaced empty values in 'building_type_Land' with 'Land'

--- Checking all building type columns ---
['building_type_1 BHK', 'building_type_2 BHK', 'building_type_3 BHK', 'building_type_4 BHK', 'building_type_5 BHK', 'building_type_6 BHK', 'building_type_1 RK', 'building_type_Land']

Replacing empty values in all building type columns...
✓ building_type_1 BHK -> replaced with '1 BHK'
✓ building_type_2 BHK -> replaced with '2 BHK'
✓ building_type_3 BHK -> replaced with '3 BHK'
✓ building_type_4 BHK -> replaced with '4 BHK'
✓ building_type_5 BHK -> replaced with '5 BHK'
✓ building_type_6 BHK -> replaced with '6 BHK'
✓ building_type_1 RK -> replaced with '1 RK'
✓ building_type_Land -> replaced with 'Land'

✓ All building type columns updated!

Sample data:
             building_type_1 BHK building_type_2 BHK building_type_3 BHK  \
PropertyName
Bahria Town            Apartment               2 BHK               3 BHK
Chaklala                   1 BHK           Apartment               3 BHK
DHA Phase 1                1 BHK               2 BHK           Apartment
DHA Phase 2                1 BHK               2 BHK               3 BHK
DHA Phase 3            Apartment               2 BHK               3 BHK

             building_type_4 BHK building_type_5 BHK building_type_6 BHK  \
PropertyName
Bahria Town                4 BHK               5 BHK               6 BHK
Chaklala                   4 BHK               5 BHK               6 BHK
DHA Phase 1                4 BHK               5 BHK               6 BHK
DHA Phase 2            Apartment               5 BHK               6 BHK
DHA Phase 3                4 BHK               5 BHK               6 BHK

             building_type_1 RK building_type_Land
PropertyName
Bahria Town                1 RK               Land
Chaklala                   1 RK               Land
DHA Phase 1                1 RK               Land
DHA Phase 2                1 RK               Land
DHA Phase 3                1 RK               Land

In [58]:

df['PriceDetails'][10]

'0.00 Crore.06 Crore | 1600 sqft | Monthly Rent: PKR 77,338'

In [60]:
df_final_refined_v2

,PropertySubName,LocationAdvantages,TopFacilities,Link,building_type_1 BHK,area_low_1 BHK,area_high_1 BHK,price_low_1 BHK,price_high_1 BHK,building_type_2 BHK,...,building_type_1 RK,area_low_1 RK,area_high_1 RK,price_low_1 RK,price_high_1 RK,building_type_Land,area_low_Land,area_high_Land,price_low_Land,price_high_Land
PropertyName,,,,,,,,,,,,,,,,,,,,,
Bahria Town,1 BHK Apartment in Bahria Town,"G-6 | Bahria Town Markets, Express Highway Acc...","[Playground, Green Area, Basketball Court]",https://www.zameen.com/Flats_Apartments/Islama...,Apartment,550.0,550.0,5.86,5.86,2 BHK,...,1 RK,None,None,None,None,Land,None,None,None,None
Chaklala,2 BHK Apartment in Chaklala,"Block B | Old Rawalpindi Area, Close to Canton...","[Generator Backup, 24/7 Security, Lifts]",https://www.zameen.com/Flats_Apartments/Islama...,1 BHK,NaN,NaN,NaN,NaN,Apartment,...,1 RK,None,None,None,None,Land,None,None,None,None
DHA Phase 1,3 BHK Apartment in DHA Phase 1,"Street 1 | DHA Main Gate, Shopping Malls, Park...","[Swimming Pool, Gym, Security, Parking]",https://www.zameen.com/Flats_Apartments/Islama...,1 BHK,NaN,NaN,NaN,NaN,2 BHK,...,1 RK,None,None,None,None,Land,None,None,None,None
DHA Phase 2,4 BHK Apartment in DHA Phase 2,"Street 10 | Centaurus Mall, Serena Hotel, Conv...","[Rooftop Garden, Lounge Area, Restaurant]",https://www.zameen.com/Flats_Apartments/Islama...,1 BHK,NaN,NaN,NaN,NaN,2 BHK,...,1 RK,None,None,None,None,Land,None,None,None,None
DHA Phase 3,1 BHK Apartment in DHA Phase 3,"Street 5 | Golf Course, Shopping Area, Green S...","[Elevator, Security Gate, CCTV, Parking]",https://www.zameen.com/Flats_Apartments/Islama...,Apartment,550.0,550.0,5.37,5.37,2 BHK,...,1 RK,None,None,None,None,Land,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
E-11,2 BHK Apartment in E-11,"Markaz | Aabpara Market, Atrium Mall, Japan Ga...","[Swimming Pool, Gym, Security, Parking]",https://www.zameen.com/Flats_Apartments/Islama...,1 BHK,NaN,NaN,NaN,NaN,Apartment,...,1 RK,None,None,None,None,Land,None,None,None,None
E-7,3 BHK Apartment in E-7,"South | Jinnah Avenue, Government Offices, Par...","[Swimming Pool, Gym, Security, Parking]",https://www.zameen.com/Flats_Apartments/Islama...,1 BHK,NaN,NaN,NaN,NaN,2 BHK,...,1 RK,None,None,None,None,Land,None,None,None,None
Gulzar-e-Quaid,4 BHK Apartment in Gulzar-e-Quaid,"Phase 2 | GT Road Access, Express Highway Prox...","[Water & Power Backup, Underground Parking]",https://www.zameen.com/Flats_Apartments/Islama...,1 BHK,NaN,NaN,NaN,NaN,2 BHK,...,1 RK,None,None,None,None,Land,None,None,None,None
I-8,1 BHK Apartment in I-8,"Markaz | Markaz Shopping, Government Institute...","[Playground, Green Area, Basketball Court]",https://www.zameen.com/Flats_Apartments/Islama...,Apartment,550.0,550.0,4.96,4.96,2 BHK,...,1 RK,None,None,None,None,Land,None,None,None,None
Margalla Hills,2 BHK Apartment in Margalla Hills,"Central | Hiking Trails, Nature Views, Scenic ...","[Water & Power Backup, Underground Parking]",https://www.zameen.com/Flats_Apartments/Islama...,1 BHK,NaN,NaN,NaN,NaN,Apartment,...,1 RK,None,None,None,None,Land,None,None,None,None

In [62]:
df_final_refined_v2 = df_final_refined_v2.drop(columns = ['PropertySubName','LocationAdvantages','TopFacilities','Link'])

In [64]:
df_final_refined_v2

,building_type_1 BHK,area_low_1 BHK,area_high_1 BHK,price_low_1 BHK,price_high_1 BHK,building_type_2 BHK,area_low_2 BHK,area_high_2 BHK,price_low_2 BHK,price_high_2 BHK,...,building_type_1 RK,area_low_1 RK,area_high_1 RK,price_low_1 RK,price_high_1 RK,building_type_Land,area_low_Land,area_high_Land,price_low_Land,price_high_Land
PropertyName,,,,,,,,,,,,,,,,,,,,,
Bahria Town,Apartment,550.0,550.0,5.86,5.86,2 BHK,NaN,NaN,NaN,NaN,...,1 RK,None,None,None,None,Land,None,None,None,None
Chaklala,1 BHK,NaN,NaN,NaN,NaN,Apartment,1120.0,1120.0,8.91,8.91,...,1 RK,None,None,None,None,Land,None,None,None,None
DHA Phase 1,1 BHK,NaN,NaN,NaN,NaN,2 BHK,NaN,NaN,NaN,NaN,...,1 RK,None,None,None,None,Land,None,None,None,None
DHA Phase 2,1 BHK,NaN,NaN,NaN,NaN,2 BHK,NaN,NaN,NaN,NaN,...,1 RK,None,None,None,None,Land,None,None,None,None
DHA Phase 3,Apartment,550.0,550.0,5.37,5.37,2 BHK,NaN,NaN,NaN,NaN,...,1 RK,None,None,None,None,Land,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
E-11,1 BHK,NaN,NaN,NaN,NaN,Apartment,1120.0,1120.0,10.49,10.49,...,1 RK,None,None,None,None,Land,None,None,None,None
E-7,1 BHK,NaN,NaN,NaN,NaN,2 BHK,NaN,NaN,NaN,NaN,...,1 RK,None,None,None,None,Land,None,None,None,None
Gulzar-e-Quaid,1 BHK,NaN,NaN,NaN,NaN,2 BHK,NaN,NaN,NaN,NaN,...,1 RK,None,None,None,None,Land,None,None,None,None
I-8,Apartment,550.0,550.0,4.96,4.96,2 BHK,NaN,NaN,NaN,NaN,...,1 RK,None,None,None,None,Land,None,None,None,None
Margalla Hills,1 BHK,NaN,NaN,NaN,NaN,Apartment,1120.0,1120.0,12.13,12.13,...,1 RK,None,None,None,None,Land,None,None,None,None

In [66]:
categorical_columns = df_final_refined_v2.select_dtypes(include=['object']).columns.tolist()

In [68]:
categorical_columns

['building_type_1 BHK',
 'building_type_2 BHK',
 'building_type_3 BHK',
 'building_type_4 BHK',
 'building_type_5 BHK',
 'area_low_5 BHK',
 'area_high_5 BHK',
 'price_low_5 BHK',
 'price_high_5 BHK',
 'building_type_6 BHK',
 'area_low_6 BHK',
 'area_high_6 BHK',
 'price_low_6 BHK',
 'price_high_6 BHK',
 'building_type_1 RK',
 'area_low_1 RK',
 'area_high_1 RK',
 'price_low_1 RK',
 'price_high_1 RK',
 'building_type_Land',
 'area_low_Land',
 'area_high_Land',
 'price_low_Land',
 'price_high_Land']

In [70]:
ohe_df = pd.get_dummies(df_final_refined_v2, columns=categorical_columns, drop_first=True)

In [72]:
ohe_df.fillna(0,inplace=True)

In [74]:
ohe_df

,area_low_1 BHK,area_high_1 BHK,price_low_1 BHK,price_high_1 BHK,area_low_2 BHK,area_high_2 BHK,price_low_2 BHK,price_high_2 BHK,area_low_3 BHK,area_high_3 BHK,price_low_3 BHK,price_high_3 BHK,area_low_4 BHK,area_high_4 BHK,price_low_4 BHK,price_high_4 BHK,building_type_1 BHK_Apartment,building_type_2 BHK_Apartment,building_type_3 BHK_Apartment,building_type_4 BHK_Apartment
PropertyName,,,,,,,,,,,,,,,,,,,,
Bahria Town,550.0,550.0,5.86,5.86,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.00,True,False,False,False
Chaklala,0.0,0.0,0.00,0.00,1120.0,1120.0,8.91,8.91,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.00,False,True,False,False
DHA Phase 1,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.00,1600.0,1600.0,18.85,18.85,0.0,0.0,0.00,0.00,False,False,True,False
DHA Phase 2,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.00,2000.0,2000.0,20.54,20.54,False,False,False,True
DHA Phase 3,550.0,550.0,5.37,5.37,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.00,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
E-11,0.0,0.0,0.00,0.00,1120.0,1120.0,10.49,10.49,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.00,False,True,False,False
E-7,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.00,1600.0,1600.0,14.92,14.92,0.0,0.0,0.00,0.00,False,False,True,False
Gulzar-e-Quaid,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.00,2000.0,2000.0,12.90,12.90,False,False,False,True
I-8,550.0,550.0,4.96,4.96,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.00,True,False,False,False
Margalla Hills,0.0,0.0,0.00,0.00,1120.0,1120.0,12.13,12.13,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.00,False,True,False,False

In [76]:
from sklearn.preprocessing import StandardScaler

# Initialize the scaler
scaler = StandardScaler()

# Apply the scaler to the entire dataframe
ohe_df_normalized = pd.DataFrame(scaler.fit_transform(ohe_df), columns=ohe_df.columns, index=ohe_df.index)

In [78]:
ohe_df_normalized.head()

,area_low_1 BHK,area_high_1 BHK,price_low_1 BHK,price_high_1 BHK,area_low_2 BHK,area_high_2 BHK,price_low_2 BHK,price_high_2 BHK,area_low_3 BHK,area_high_3 BHK,price_low_3 BHK,price_high_3 BHK,area_low_4 BHK,area_high_4 BHK,price_low_4 BHK,price_high_4 BHK,building_type_1 BHK_Apartment,building_type_2 BHK_Apartment,building_type_3 BHK_Apartment,building_type_4 BHK_Apartment
PropertyName,,,,,,,,,,,,,,,,,,,,
Bahria Town,1.722862,1.722862,1.986229,1.986229,-0.580429,-0.580429,-0.569194,-0.569194,-0.574271,-0.574271,-0.550717,-0.550717,-0.574271,-0.574271,-0.545793,-0.545793,1.722862,-0.580429,-0.574271,-0.574271
Chaklala,-0.580429,-0.580429,-0.577652,-0.577652,1.722862,1.722862,1.314925,1.314925,-0.574271,-0.574271,-0.550717,-0.550717,-0.574271,-0.574271,-0.545793,-0.545793,-0.580429,1.722862,-0.574271,-0.574271
DHA Phase 1,-0.580429,-0.580429,-0.577652,-0.577652,-0.580429,-0.580429,-0.569194,-0.569194,1.741338,1.741338,2.201030,2.201030,-0.574271,-0.574271,-0.545793,-0.545793,-0.580429,-0.580429,1.741338,-0.574271
DHA Phase 2,-0.580429,-0.580429,-0.577652,-0.577652,-0.580429,-0.580429,-0.569194,-0.569194,-0.574271,-0.574271,-0.550717,-0.550717,1.741338,1.741338,2.347561,2.347561,-0.580429,-0.580429,-0.574271,1.741338
DHA Phase 3,1.722862,1.722862,1.771843,1.771843,-0.580429,-0.580429,-0.569194,-0.569194,-0.574271,-0.574271,-0.550717,-0.550717,-0.574271,-0.574271,-0.545793,-0.545793,1.722862,-0.580429,-0.574271,-0.574271

In [80]:
from sklearn.metrics.pairwise import cosine_similarity

# Compute the cosine similarity matrix
cosine_sim2 = cosine_similarity(ohe_df_normalized)

In [82]:
cosine_sim2.shape

(250, 250)

In [84]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pandas as pd

def recommend_properties_with_scores(property_name, top_n=5):
    """
    Recommend properties based on cosine similarity
    """
    try:
        # Check if property exists
        if property_name not in ohe_df_normalized.index:
            print(f"✗ Property '{property_name}' not found!")
            return None
        
        print(f"\n✓ Found property: '{property_name}'")
        
        # Calculate cosine similarity
        print("✓ Calculating cosine similarity...")
        cosine_sim = cosine_similarity(ohe_df_normalized)
        
        # Ensure it's a numpy array
        cosine_sim = np.array(cosine_sim)
        cosine_sim = np.nan_to_num(cosine_sim, nan=0.0)
        
        print(f"✓ Cosine similarity shape: {cosine_sim.shape}")
        
        # FIX: Use where() instead of get_loc() to get proper index
        property_indices = np.where(ohe_df_normalized.index == property_name)[0]
        
        if len(property_indices) == 0:
            print(f"✗ Property '{property_name}' not found!")
            return None
        
        property_idx = property_indices[0]  # Get first match
        print(f"✓ Property index: {property_idx}")
        
        # Get similarity scores for this property
        sim_scores = cosine_sim[property_idx]
        print(f"✓ Similarity scores type: {type(sim_scores)}, shape: {sim_scores.shape}")
        
        # Create list of (index, score) tuples
        sim_list = [(i, float(sim_scores[i])) for i in range(len(sim_scores))]
        
        # Sort by score (descending)
        sorted_scores = sorted(sim_list, key=lambda x: x[1], reverse=True)
        
        # Get top_n (skip first - it's the property itself)
        top_indices = [i[0] for i in sorted_scores[1:top_n+1]]
        top_scores = [i[1] for i in sorted_scores[1:top_n+1]]
        
        # Get property names
        recommendations = ohe_df_normalized.index[top_indices].tolist()
        
        # Create dataframe
        recommendations_df = pd.DataFrame({
            'PropertyName': recommendations,
            'Similarity_Score': top_scores
        })
        
        print(f"\n✓ Top {top_n} recommendations for '{property_name}':\n")
        print(recommendations_df.to_string(index=False))
        
        return recommendations_df
    
    except Exception as e:
        print(f"✗ Error: {str(e)}")
        import traceback
        traceback.print_exc()
        return None

# Test the function
print("=" * 60)
print("TESTING RECOMMENDATION FUNCTION")
print("=" * 60)
result = recommend_properties_with_scores('DHA Phase 1')

============================================================
TESTING RECOMMENDATION FUNCTION
============================================================

✓ Found property: 'DHA Phase 1'
✓ Calculating cosine similarity...
✓ Cosine similarity shape: (250, 250)
✓ Property index: 2
✓ Similarity scores type: <class 'numpy.ndarray'>, shape: (250,)

✓ Top 5 recommendations for 'DHA Phase 1':

PropertyName  Similarity_Score
 DHA Phase 1          0.999995
 DHA Phase 1          0.999974
 DHA Phase 1          0.999886
 DHA Phase 1          0.999863
 DHA Phase 1          0.999844

In [86]:
df[['PropertyName','LocationAdvantages']]['LocationAdvantages'][0]

'G-6 | Bahria Town Markets, Express Highway Access, Blue Area Proximity | Distance: 1-3 KM to main markets'

In [88]:
def distance_to_meters(distance_str):
    try:
        if 'Km' in distance_str or 'KM' in distance_str:
            return float(distance_str.split()[0]) * 1000
        elif 'Meter' in distance_str or 'meter' in distance_str:
            return float(distance_str.split()[0])
        else:
            return None
    except:
        return None

In [90]:
import pandas as pd
import numpy as np

# Load your apartments dataset
df = pd.read_excel('Islamabad_Apartments_250_Final.xlsx')

# Define major landmarks/locations (exact column names like your example)
landmarks = [
    'Jinnah Avenue', 'Blue Area', 'Centaurus Mall', 'Serena Hotel', 'PIMS Hospital',
    'Aabpara Market', 'Atrium Mall', 'Rawal Lake', 'Pakistan Monument', 'Convention Center',
    'Rose & Jasmine Road', 'GT Road', 'Expressway', 'Airport Road', 'Margalla Hills',
    'Shakarparian', 'Civic Center', 'Melody Market', 'Hyperstar', 'F-9 Park'
]

# Create location_matrix dictionary
location_matrix = {}

for index, row in df.iterrows():
    distances = {}
    
    # For each landmark, randomly assign distance or NaN
    for landmark in landmarks:
        # 50% chance of having a distance, 50% NaN
        if np.random.random() > 0.5:
            # Random distance between 500m and 25000m (0.5 to 25 KM)
            distance = np.random.randint(500, 25000)
            distances[landmark] = distance
        else:
            distances[landmark] = np.nan
    
    location_matrix[index] = distances

# Convert dictionary to dataframe (index = property ID)
location_df = pd.DataFrame.from_dict(location_matrix, orient='index')

# Display info
print("Location Matrix Created!")
print(f"Shape: {location_df.shape} (rows × columns)")
print(f"Total properties: {len(location_df)}")
print(f"Total landmarks: {len(location_df.columns)}")
print("\nFirst few rows:")
print(location_df.head(10))




# Display sample
print("\n--- Sample Output (like your screenshot) ---")
location_df.head()

Location Matrix Created!
Shape: (250, 20) (rows × columns)
Total properties: 250
Total landmarks: 20

First few rows:
   Jinnah Avenue  Blue Area  Centaurus Mall  Serena Hotel  PIMS Hospital  \
0            NaN     1186.0         24017.0           NaN         6992.0
1         6660.0    16914.0         23390.0         832.0        18110.0
2            NaN     1650.0             NaN           NaN        20410.0
3         7659.0        NaN             NaN       10696.0        18910.0
4            NaN        NaN             NaN           NaN        22554.0
5        19387.0        NaN         14998.0        6307.0            NaN
6        24492.0        NaN          5566.0       18939.0        14689.0
7            NaN     5278.0             NaN           NaN            NaN
8            NaN        NaN          2760.0       11407.0        23426.0
9            NaN        NaN             NaN        9408.0        19368.0

   Aabpara Market  Atrium Mall  Rawal Lake  Pakistan Monument  \
0             NaN          NaN     24198.0             5138.0
1         15939.0      12512.0     21581.0            10829.0
2         14976.0       1922.0      9557.0                NaN
3             NaN          NaN     18714.0                NaN
4             NaN       5899.0         NaN            22299.0
5             NaN      13471.0         NaN                NaN
6         24581.0      22634.0     22035.0                NaN
7             NaN      19418.0         NaN             2172.0
8         16955.0          NaN     23234.0             6083.0
9             NaN          NaN         NaN            15434.0

   Convention Center  Rose & Jasmine Road  GT Road  Expressway  Airport Road  \
0                NaN              23451.0      NaN         NaN       24626.0
1                NaN              12308.0  15406.0         NaN           NaN
2            22488.0              24346.0      NaN         NaN           NaN
3                NaN                  NaN      NaN     20924.0           NaN
4            14203.0                  NaN      NaN     19458.0       16019.0
5            15107.0               5627.0  10416.0      9675.0        6400.0
6                NaN              23320.0      NaN     23871.0           NaN
7                NaN                  NaN      NaN     21914.0           NaN
8                NaN               8225.0  18726.0      7614.0       13313.0
9                NaN              15323.0      NaN         NaN        7630.0

   Margalla Hills  Shakarparian  Civic Center  Melody Market  Hyperstar  \
0             NaN           NaN       14316.0            NaN        NaN
1             NaN       15587.0           NaN        23791.0        NaN
2             NaN        1459.0        7960.0         1248.0     5934.0
3         11621.0           NaN           NaN            NaN      547.0
4             NaN        7935.0           NaN            NaN     1358.0
5             NaN           NaN       12923.0        13774.0    21638.0
6         24225.0       19693.0       15442.0            NaN        NaN
7             NaN       23385.0        9372.0            NaN     4731.0
8         22044.0           NaN           NaN        12239.0        NaN
9         17684.0           NaN        5491.0            NaN    20471.0

   F-9 Park
0    7099.0
1       NaN
2       NaN
3   13366.0
4       NaN
5       NaN
6    6805.0
7       NaN
8       NaN
9       NaN

--- Sample Output (like your screenshot) ---

,Jinnah Avenue,Blue Area,Centaurus Mall,Serena Hotel,PIMS Hospital,Aabpara Market,Atrium Mall,Rawal Lake,Pakistan Monument,Convention Center,Rose & Jasmine Road,GT Road,Expressway,Airport Road,Margalla Hills,Shakarparian,Civic Center,Melody Market,Hyperstar,F-9 Park
0,NaN,1186.0,24017.0,NaN,6992.0,NaN,NaN,24198.0,5138.0,NaN,23451.0,NaN,NaN,24626.0,NaN,NaN,14316.0,NaN,NaN,7099.0
1,6660.0,16914.0,23390.0,832.0,18110.0,15939.0,12512.0,21581.0,10829.0,NaN,12308.0,15406.0,NaN,NaN,NaN,15587.0,NaN,23791.0,NaN,NaN
2,NaN,1650.0,NaN,NaN,20410.0,14976.0,1922.0,9557.0,NaN,22488.0,24346.0,NaN,NaN,NaN,NaN,1459.0,7960.0,1248.0,5934.0,NaN
3,7659.0,NaN,NaN,10696.0,18910.0,NaN,NaN,18714.0,NaN,NaN,NaN,NaN,20924.0,NaN,11621.0,NaN,NaN,NaN,547.0,13366.0
4,NaN,NaN,NaN,NaN,22554.0,NaN,5899.0,NaN,22299.0,14203.0,NaN,NaN,19458.0,16019.0,NaN,7935.0,NaN,NaN,1358.0,NaN

In [92]:
location_df.columns[10:50]

Index(['Rose & Jasmine Road', 'GT Road', 'Expressway', 'Airport Road',
       'Margalla Hills', 'Shakarparian', 'Civic Center', 'Melody Market',
       'Hyperstar', 'F-9 Park'],
      dtype='object')

In [94]:

location_df.index = df.PropertyName

In [96]:
location_df.head()

,Jinnah Avenue,Blue Area,Centaurus Mall,Serena Hotel,PIMS Hospital,Aabpara Market,Atrium Mall,Rawal Lake,Pakistan Monument,Convention Center,Rose & Jasmine Road,GT Road,Expressway,Airport Road,Margalla Hills,Shakarparian,Civic Center,Melody Market,Hyperstar,F-9 Park
PropertyName,,,,,,,,,,,,,,,,,,,,
Bahria Town - G-6 - Unit 1,NaN,1186.0,24017.0,NaN,6992.0,NaN,NaN,24198.0,5138.0,NaN,23451.0,NaN,NaN,24626.0,NaN,NaN,14316.0,NaN,NaN,7099.0
Chaklala - Block B - Unit 2,6660.0,16914.0,23390.0,832.0,18110.0,15939.0,12512.0,21581.0,10829.0,NaN,12308.0,15406.0,NaN,NaN,NaN,15587.0,NaN,23791.0,NaN,NaN
DHA Phase 1 - Street 1 - Unit 3,NaN,1650.0,NaN,NaN,20410.0,14976.0,1922.0,9557.0,NaN,22488.0,24346.0,NaN,NaN,NaN,NaN,1459.0,7960.0,1248.0,5934.0,NaN
DHA Phase 2 - Street 10 - Unit 4,7659.0,NaN,NaN,10696.0,18910.0,NaN,NaN,18714.0,NaN,NaN,NaN,NaN,20924.0,NaN,11621.0,NaN,NaN,NaN,547.0,13366.0
DHA Phase 3 - Street 5 - Unit 5,NaN,NaN,NaN,NaN,22554.0,NaN,5899.0,NaN,22299.0,14203.0,NaN,NaN,19458.0,16019.0,NaN,7935.0,NaN,NaN,1358.0,NaN

In [98]:

location_df.fillna(54000,inplace=True)

In [100]:
location_df

,Jinnah Avenue,Blue Area,Centaurus Mall,Serena Hotel,PIMS Hospital,Aabpara Market,Atrium Mall,Rawal Lake,Pakistan Monument,Convention Center,Rose & Jasmine Road,GT Road,Expressway,Airport Road,Margalla Hills,Shakarparian,Civic Center,Melody Market,Hyperstar,F-9 Park
PropertyName,,,,,,,,,,,,,,,,,,,,
Bahria Town - G-6 - Unit 1,54000.0,1186.0,24017.0,54000.0,6992.0,54000.0,54000.0,24198.0,5138.0,54000.0,23451.0,54000.0,54000.0,24626.0,54000.0,54000.0,14316.0,54000.0,54000.0,7099.0
Chaklala - Block B - Unit 2,6660.0,16914.0,23390.0,832.0,18110.0,15939.0,12512.0,21581.0,10829.0,54000.0,12308.0,15406.0,54000.0,54000.0,54000.0,15587.0,54000.0,23791.0,54000.0,54000.0
DHA Phase 1 - Street 1 - Unit 3,54000.0,1650.0,54000.0,54000.0,20410.0,14976.0,1922.0,9557.0,54000.0,22488.0,24346.0,54000.0,54000.0,54000.0,54000.0,1459.0,7960.0,1248.0,5934.0,54000.0
DHA Phase 2 - Street 10 - Unit 4,7659.0,54000.0,54000.0,10696.0,18910.0,54000.0,54000.0,18714.0,54000.0,54000.0,54000.0,54000.0,20924.0,54000.0,11621.0,54000.0,54000.0,54000.0,547.0,13366.0
DHA Phase 3 - Street 5 - Unit 5,54000.0,54000.0,54000.0,54000.0,22554.0,54000.0,5899.0,54000.0,22299.0,14203.0,54000.0,54000.0,19458.0,16019.0,54000.0,7935.0,54000.0,54000.0,1358.0,54000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
E-11 - Markaz - Unit 246,18849.0,23748.0,54000.0,15792.0,54000.0,54000.0,9582.0,22451.0,14369.0,54000.0,22313.0,6202.0,54000.0,6052.0,54000.0,13906.0,54000.0,54000.0,8777.0,54000.0
E-7 - South - Unit 247,54000.0,22741.0,54000.0,54000.0,12951.0,619.0,10950.0,12695.0,10371.0,54000.0,6581.0,54000.0,54000.0,13351.0,54000.0,7497.0,54000.0,675.0,54000.0,5891.0
Gulzar-e-Quaid - Phase 2 - Unit 248,54000.0,54000.0,17460.0,54000.0,54000.0,10006.0,8904.0,54000.0,16623.0,54000.0,4355.0,1828.0,54000.0,9716.0,54000.0,14446.0,17732.0,9044.0,54000.0,54000.0
I-8 - Markaz - Unit 249,54000.0,54000.0,22971.0,54000.0,54000.0,17513.0,54000.0,54000.0,54000.0,1266.0,54000.0,54000.0,54000.0,14547.0,54000.0,54000.0,3055.0,54000.0,54000.0,54000.0
Margalla Hills - Central - Unit 250,54000.0,14188.0,54000.0,54000.0,54000.0,19867.0,54000.0,54000.0,3454.0,54000.0,54000.0,11232.0,6771.0,54000.0,54000.0,54000.0,54000.0,54000.0,20225.0,10450.0

In [102]:
from sklearn.preprocessing import StandardScaler
# Initialize the scaler
scaler = StandardScaler()

# Apply the scaler to the entire dataframe
location_df_normalized = pd.DataFrame(scaler.fit_transform(location_df), columns=location_df.columns, index=location_df.index)

In [104]:
location_df_normalized

,Jinnah Avenue,Blue Area,Centaurus Mall,Serena Hotel,PIMS Hospital,Aabpara Market,Atrium Mall,Rawal Lake,Pakistan Monument,Convention Center,Rose & Jasmine Road,GT Road,Expressway,Airport Road,Margalla Hills,Shakarparian,Civic Center,Melody Market,Hyperstar,F-9 Park
PropertyName,,,,,,,,,,,,,,,,,,,,
Bahria Town - G-6 - Unit 1,0.942350,-1.449502,-0.391993,1.007517,-1.233950,1.004117,0.989080,-0.500991,-1.277631,0.924586,-0.549671,0.885052,1.032394,-0.374641,0.974137,0.985242,-0.933376,0.993630,0.942528,-1.226095
Chaklala - Block B - Unit 2,-1.271460,-0.710406,-0.421307,-1.528006,-0.691781,-0.790965,-0.997274,-0.624975,-1.009907,0.924586,-1.084234,-0.966583,1.032394,0.982285,0.974137,-0.843841,0.909805,-0.444531,0.942528,0.914290
DHA Phase 1 - Street 1 - Unit 3,0.942350,-1.427698,1.009801,1.007517,-0.579621,-0.836383,-1.504300,-1.194628,1.021009,-0.588238,-0.506735,0.885052,1.032394,0.982285,0.974137,-1.516564,-1.228589,-1.517736,-1.295691,0.914290
DHA Phase 2 - Street 10 - Unit 4,-1.224743,1.032352,1.009801,-1.057603,-0.652769,1.004117,0.989080,-0.760803,1.021009,0.924586,0.915856,0.885052,-0.510766,0.982285,-1.074286,0.985242,0.909805,0.993630,-1.546539,-0.940092
DHA Phase 3 - Street 5 - Unit 5,0.942350,1.032352,1.009801,1.007517,-0.475069,1.004117,-1.313890,0.910918,-0.470318,-0.985984,0.915856,0.885052,-0.579162,-0.772239,0.974137,-1.208201,0.909805,0.993630,-1.508775,0.914290
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
E-11 - Markaz - Unit 246,-0.701453,-0.389260,1.009801,-0.814580,1.058396,1.004117,-1.137556,-0.583758,-0.843373,0.924586,-0.604264,-1.408165,1.032394,-1.232663,0.974137,-0.923884,0.909805,0.993630,-1.163305,0.914290
E-7 - South - Unit 247,0.942350,-0.436582,1.009801,1.007517,-0.943360,-1.513506,-1.072059,-1.045961,-1.031453,0.924586,-1.358975,0.885052,1.032394,-0.895487,0.974137,-1.229057,0.909805,-1.545015,0.942528,-1.281223
Gulzar-e-Quaid - Phase 2 - Unit 248,0.942350,1.032352,-0.698552,1.007517,1.058396,-1.070784,-1.170017,0.910918,-0.737337,0.924586,-1.465763,-1.618018,1.032394,-1.063405,0.974137,-0.898171,-0.774715,-1.146592,0.942528,0.914290
I-8 - Markaz - Unit 249,0.942350,1.032352,-0.440896,1.007517,1.058396,-0.716730,0.989080,0.910918,1.021009,-1.607062,0.915856,0.885052,1.032394,-0.840238,0.974137,0.985242,-1.456409,0.993630,0.942528,0.914290
Margalla Hills - Central - Unit 250,0.942350,-0.838507,1.009801,1.007517,1.058396,-0.605707,0.989080,0.910918,-1.356853,0.924586,0.915856,-1.166840,-1.171073,0.982285,0.974137,0.985242,0.909805,0.993630,-0.630223,-1.073168

In [106]:

cosine_sim3 = cosine_similarity(location_df_normalized)

In [108]:
cosine_sim3.shape

(250, 250)

In [111]:
def recommend_properties_with_scores(property_name, top_n=247):
    
    cosine_sim_matrix = 30*cosine_sim1 + 20*cosine_sim2 + 8*cosine_sim3
    # cosine_sim_matrix = cosine_sim3
    
    # Get the similarity scores for the property using its name as the index
    sim_scores = list(enumerate(cosine_sim_matrix[location_df_normalized.index.get_loc(property_name)]))
    
    # Sort properties based on the similarity scores
    sorted_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # Get the indices and scores of the top_n most similar properties
    top_indices = [i[0] for i in sorted_scores[1:top_n+1]]
    top_scores = [i[1] for i in sorted_scores[1:top_n+1]]
    
    # Retrieve the names of the top properties using the indices
    top_properties = location_df_normalized.index[top_indices].tolist()
    
    # Create a dataframe with the results
    recommendations_df = pd.DataFrame({
        'PropertyName': top_properties,
        'SimilarityScore': top_scores
    })
    
    return recommendations_df

# Test the recommender function using a property name
recommend_properties_with_scores('Margalla Hills - Central - Unit 250')

                            PropertyName  SimilarityScore
0          Chaklala - Block C - Unit 134        51.463254
1               E-11 - Markaz - Unit 150        49.259664
2       Margalla Hills - South - Unit 46        49.143581
3                 E-11 - Markaz - Unit 6        47.579884
4              Sadiqabad - New - Unit 48        25.523126
..                                   ...              ...
242  Gulzar-e-Quaid - Phase 2 - Unit 116        -9.329452
243    DHA Phase 2 - Street 5 - Unit 148        -9.469023
244                 E-7 - North - Unit 7        -9.476298
245    DHA Phase 2 - Street 15 - Unit 76        -9.651666
246    DHA Phase 3 - Street 10 - Unit 53        -9.653053

[247 rows x 2 columns]

In [113]:
df['PropertyName']

0               Bahria Town - G-6 - Unit 1
1              Chaklala - Block B - Unit 2
2          DHA Phase 1 - Street 1 - Unit 3
3         DHA Phase 2 - Street 10 - Unit 4
4          DHA Phase 3 - Street 5 - Unit 5
                      ...
245               E-11 - Markaz - Unit 246
246                 E-7 - South - Unit 247
247    Gulzar-e-Quaid - Phase 2 - Unit 248
248                I-8 - Markaz - Unit 249
249    Margalla Hills - Central - Unit 250
Name: PropertyName, Length: 250, dtype: object

In [115]:
recommend_properties_with_scores('E-11 - Markaz - Unit 246')

                            PropertyName  SimilarityScore
0          Chaklala - Block A - Unit 194        52.681087
1    Margalla Hills - Central - Unit 238        52.387744
2      Margalla Hills - South - Unit 154        51.020691
3    Margalla Hills - Central - Unit 178        50.226731
4          Chaklala - Block D - Unit 182        49.322011
..                                   ...              ...
242    DHA Phase 1 - Street 5 - Unit 171        -9.264611
243           Sadiqabad - New - Unit 168        -9.362736
244              I-8 - Markaz - Unit 249        -9.434497
245                 E-7 - North - Unit 7        -9.469674
246    DHA Phase 3 - Street 10 - Unit 89        -9.650867

[247 rows x 2 columns]

In [117]:
cosine_sim1

array([[1.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 1.        , 0.05638607, ..., 0.07882975, 0.        ,
        0.07882975],
       [0.        , 0.05638607, 1.        , ..., 0.05646377, 0.        ,
        0.05646377],
       ...,
       [0.        , 0.07882975, 0.05646377, ..., 1.        , 0.        ,
        1.        ],
       [1.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.07882975, 0.05646377, ..., 1.        , 0.        ,
        1.        ]])

In [119]:
cosine_sim2

array([[ 1.        , -0.3424665 , -0.33006678, ..., -0.33261811,
         0.99475109, -0.34062551],
       [-0.3424665 ,  1.        , -0.3295011 , ..., -0.32540776,
        -0.34194824,  0.98280066],
       [-0.33006678, -0.3295011 ,  1.        , ..., -0.32009039,
        -0.33238466, -0.32748454],
       ...,
       [-0.33261811, -0.32540776, -0.32009039, ...,  1.        ,
        -0.33141743, -0.3297116 ],
       [ 0.99475109, -0.34194824, -0.33238466, ..., -0.33141743,
         1.        , -0.34274805],
       [-0.34062551,  0.98280066, -0.32748454, ..., -0.3297116 ,
        -0.34274805,  1.        ]])

In [121]:
cosine_sim3

array([[ 1.        , -0.05381141, -0.0366195 , ..., -0.06251383,
         0.10096525,  0.18722103],
       [-0.05381141,  1.        ,  0.13284148, ...,  0.28431467,
        -0.47890758, -0.18040554],
       [-0.0366195 ,  0.13284148,  1.        , ...,  0.14687988,
        -0.03219587, -0.25934031],
       ...,
       [-0.06251383,  0.28431467,  0.14687988, ...,  1.        ,
         0.16940909, -0.06988799],
       [ 0.10096525, -0.47890758, -0.03219587, ...,  0.16940909,
         1.        , -0.05719004],
       [ 0.18722103, -0.18040554, -0.25934031, ..., -0.06988799,
        -0.05719004,  1.        ]])

In [123]:
(3*cosine_sim3 + 5*cosine_sim2 + 6*cosine_sim1).shape

(250, 250)

In [125]:
location_df

,Jinnah Avenue,Blue Area,Centaurus Mall,Serena Hotel,PIMS Hospital,Aabpara Market,Atrium Mall,Rawal Lake,Pakistan Monument,Convention Center,Rose & Jasmine Road,GT Road,Expressway,Airport Road,Margalla Hills,Shakarparian,Civic Center,Melody Market,Hyperstar,F-9 Park
PropertyName,,,,,,,,,,,,,,,,,,,,
Bahria Town - G-6 - Unit 1,54000.0,1186.0,24017.0,54000.0,6992.0,54000.0,54000.0,24198.0,5138.0,54000.0,23451.0,54000.0,54000.0,24626.0,54000.0,54000.0,14316.0,54000.0,54000.0,7099.0
Chaklala - Block B - Unit 2,6660.0,16914.0,23390.0,832.0,18110.0,15939.0,12512.0,21581.0,10829.0,54000.0,12308.0,15406.0,54000.0,54000.0,54000.0,15587.0,54000.0,23791.0,54000.0,54000.0
DHA Phase 1 - Street 1 - Unit 3,54000.0,1650.0,54000.0,54000.0,20410.0,14976.0,1922.0,9557.0,54000.0,22488.0,24346.0,54000.0,54000.0,54000.0,54000.0,1459.0,7960.0,1248.0,5934.0,54000.0
DHA Phase 2 - Street 10 - Unit 4,7659.0,54000.0,54000.0,10696.0,18910.0,54000.0,54000.0,18714.0,54000.0,54000.0,54000.0,54000.0,20924.0,54000.0,11621.0,54000.0,54000.0,54000.0,547.0,13366.0
DHA Phase 3 - Street 5 - Unit 5,54000.0,54000.0,54000.0,54000.0,22554.0,54000.0,5899.0,54000.0,22299.0,14203.0,54000.0,54000.0,19458.0,16019.0,54000.0,7935.0,54000.0,54000.0,1358.0,54000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
E-11 - Markaz - Unit 246,18849.0,23748.0,54000.0,15792.0,54000.0,54000.0,9582.0,22451.0,14369.0,54000.0,22313.0,6202.0,54000.0,6052.0,54000.0,13906.0,54000.0,54000.0,8777.0,54000.0
E-7 - South - Unit 247,54000.0,22741.0,54000.0,54000.0,12951.0,619.0,10950.0,12695.0,10371.0,54000.0,6581.0,54000.0,54000.0,13351.0,54000.0,7497.0,54000.0,675.0,54000.0,5891.0
Gulzar-e-Quaid - Phase 2 - Unit 248,54000.0,54000.0,17460.0,54000.0,54000.0,10006.0,8904.0,54000.0,16623.0,54000.0,4355.0,1828.0,54000.0,9716.0,54000.0,14446.0,17732.0,9044.0,54000.0,54000.0
I-8 - Markaz - Unit 249,54000.0,54000.0,22971.0,54000.0,54000.0,17513.0,54000.0,54000.0,54000.0,1266.0,54000.0,54000.0,54000.0,14547.0,54000.0,54000.0,3055.0,54000.0,54000.0,54000.0
Margalla Hills - Central - Unit 250,54000.0,14188.0,54000.0,54000.0,54000.0,19867.0,54000.0,54000.0,3454.0,54000.0,54000.0,11232.0,6771.0,54000.0,54000.0,54000.0,54000.0,54000.0,20225.0,10450.0

In [127]:
 import pickle

In [129]:
pickle.dump(location_df,open('location_distance.pkl','wb'))

In [136]:
pickle.dump(location_df,open('cosine_sim1','wb'))
pickle.dump(location_df,open('cosine_sim2','wb'))
pickle.dump(location_df,open('cosine_sim3','wb'))